### ISSUE TITLE
TestBoolean2.testRandomQueries fails in CI due to eating up heap space

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11754]
### Description

Jenkins failure (sorry I don't have full build log, but the failure is reproducible, see below):

```
[JENKINS] Lucene-main-Linux (64bit/jdk-17.0.3) - Build # 36812 - Unstable!
Build: https://jenkins.thetaphi.de/job/Lucene-main-Linux/36812/
Java: 64bit/jdk-17.0.3 -XX:-UseCompressedOops -XX:+UseParallelGC

1 tests failed.
FAILED: org.apache.lucene.search.TestBoolean2.testRandomQueries

Error Message:
java.lang.OutOfMemoryError: Java heap space

Stack Trace:
java.lang.OutOfMemoryError: Java heap space
at __randomizedtesting.SeedInfo.seed([A0883CC08C1C22AB:FEA38C2CB4C60F35]:0)
at org.apache.lucene.util.PriorityQueue.<init>(PriorityQueue.java:96)
at org.apache.lucene.util.PriorityQueue.<init>(PriorityQueue.java:43)
at org.apache.lucene.search.FieldValueHitQueue.<init>(FieldValueHitQueue.java:123)
at org.apache.lucene.search.FieldValueHitQueue$OneComparatorFieldValueHitQueue.<init>(FieldValueHitQueue.java:59)
at org.apache.lucene.search.FieldValueHitQueue.create(FieldValueHitQueue.java:159)
at org.apache.lucene.search.TopFieldCollector.create(TopFieldCollector.java:454)
at org.apache.lucene.search.TopFieldCollector$1.newCollector(TopFieldCollector.java:501)
at org.apache.lucene.search.TopFieldCollector$1.newCollector(TopFieldCollector.java:493)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:669)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:656)
at org.apache.lucene.search.TestBoolean2.testRandomQueries(TestBoolean2.java:406)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
```

### Gradle command to reproduce

Reproduce with:

`./gradlew -p lucene/core -Ptests.seed=A0883CC08C1C22AB -Ptests.heapsize=256m -Ptests.minheapsize=256m -Ptests.multiplier=3 test --tests TestBoolean2.testRandomQueries`

The test is well-behaved without the `multiplier=3` so this may be related to the issue.

**Comment by javanna** [comment]
Still relevant, I think the factor is the number of segments perhaps and how they get searched concurrently (e.g. number of slices), because each slice gets its own collector with its own queue, and that seems to blow up the heap space in certain conditions. I am observing the same problem in #13542 .

**Comment by rmuir** [comment]
@javanna if you can reproduce it again, can you try `System.out.println(mulFactor)` at the end of the BeforeClass method?

OOM in the stacktrace comes from creating priorityqueue of `1000 * mulFactor`. Then if we look at `@BeforeClass` where the `mulFactor` gets set, it isn't even constant, it is set dynamically, with exponential (!) growth like this:

```java
    do {
      addIndexes();
      ...
      mulFactor *= 2;
    } while (docCount < 3000 * NUM_FILLER_DOCS);
```

I think the fact it grows index and pq size (mulFactor) exponentially, may be the reason for the trouble. half of the time (NUM_FILLER_DOCS=4k) it creates 12M document index. 

in some rare situations (PRE_FILLER_DOCS small or zero) it looks like it may need to addIndexes() 12 times to do this and so I think `mulFactor` can get high such as `4K`? And I think that leads to asking for millions of results at once (1000 * 4096) and causes the OOM.

**Comment by javanna** [comment]
You are correct @rmuir !

In my case, `mulFactor` is `1024`. My branch makes it even more likely to go out of heap space, because it may create more slices to be searched concurrently, and each slice gets a separate collector with a separate queue of that size. We could disable query concurrency for this test, or work on limiting the number of slices. On the other hand, I don't understand the purpose of `1000 * mulFactor`. If I use `mulFactor` as the size of the queue, the test still succeeds and it no longer goes out of heap for my failing seed. Maybe that's a reasonable fix?

**Comment by rmuir** [comment]
@javanna I don't understand the test, but we need to tone down its craziness. Removing 1000 sounds great to me, if the single line change makes the test a thousand times less annoying then we succeeded.

**Comment by javanna** [comment]
Agreed, I opened #13713
