### ISSUE TITLE
Reproducible TestShapeDocValues failure

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#11829]
### Description

The test seems to be creating invalid polygons.

```
03:40:22 org.apache.lucene.document.TestShapeDocValues > testXYPolygonCentroid FAILED
03:40:22 WARNING: The Security Manager is deprecated and will be removed in a future release
03:40:22     java.lang.IllegalArgumentException: Polygon self-intersection at lat=2.9067992002286562 lon=6.0168174085684076E7
03:40:22         at __randomizedtesting.SeedInfo.seed([29AE25A2D4FB94F9:CC0CD5ABA2A74207]:0)
03:40:22         at org.apache.lucene.geo.Tessellator.checkIntersectionPoint(Tessellator.java:958)
03:40:22         at org.apache.lucene.geo.Tessellator.checkIntersection(Tessellator.java:870)
03:40:22         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:198)
03:40:22         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:152)
03:40:22         at org.apache.lucene.document.XYShape.createIndexableFields(XYShape.java:99)
03:40:22         at org.apache.lucene.document.TestShapeDocValues.getTessellation(TestShapeDocValues.java:249)
03:40:22         at org.apache.lucene.document.TestShapeDocValues.getTessellation(TestShapeDocValues.java:232)
03:40:22         at org.apache.lucene.document.TestShapeDocValues.computeCentroid(TestShapeDocValues.java:98)
03:40:22         at org.apache.lucene.document.TestShapeDocValues.testXYPolygonCentroid(TestShapeDocValues.java:90)
03:40:22         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:40:22         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
03:40:22         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:22         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
03:40:22         at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
03:40:22         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
03:40:22         at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
03:40:22         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
03:40:22         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
03:40:22         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
03:40:22         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
03:40:22         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
03:40:22         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
03:40:22         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
03:40:22         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
03:40:22         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22         at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
03:40:22         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
03:40:22         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
03:40:22         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22         at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
03:40:22         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
03:40:22         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
03:40:22         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
03:40:22         at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
03:40:22         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
03:40:22         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
03:40:22         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
03:40:22         at java.base/java.lang.Thread.run(Thread.java:833)
03:40:22 
03:40:22 org.apache.lucene.document.TestShapeDocValues > test suite's output saved to /var/lib/jenkins/workspace/apache+lucene+main/lucene/core/build/test-results/test/outputs/OUTPUT-org.apache.lucene.document.TestShapeDocValues.txt, copied below:
03:40:22    >     java.lang.IllegalArgumentException: Polygon self-intersection at lat=2.9067992002286562 lon=6.0168174085684076E7
03:40:22    >         at __randomizedtesting.SeedInfo.seed([29AE25A2D4FB94F9:CC0CD5ABA2A74207]:0)
03:40:22    >         at org.apache.lucene.geo.Tessellator.checkIntersectionPoint(Tessellator.java:958)
03:40:22    >         at org.apache.lucene.geo.Tessellator.checkIntersection(Tessellator.java:870)
03:40:22    >         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:198)
03:40:22    >         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:152)
03:40:22    >         at org.apache.lucene.document.XYShape.createIndexableFields(XYShape.java:99)
03:40:22    >         at org.apache.lucene.document.TestShapeDocValues.getTessellation(TestShapeDocValues.java:249)
03:40:22    >         at org.apache.lucene.document.TestShapeDocValues.getTessellation(TestShapeDocValues.java:232)
03:40:22    >         at org.apache.lucene.document.TestShapeDocValues.computeCentroid(TestShapeDocValues.java:98)
03:40:22    >         at org.apache.lucene.document.TestShapeDocValues.testXYPolygonCentroid(TestShapeDocValues.java:90)
03:40:22    >         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:40:22    >         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
03:40:22    >         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:40:22    >         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
03:40:22    >         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
03:40:22    >         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22    >         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
03:40:22    >         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
03:40:22    >         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
03:40:22    >         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
03:40:22    >         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
03:40:22    >         at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
03:40:22    >         at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
03:40:22    >         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
03:40:22    >         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
03:40:22    >         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
03:40:22    >         at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
03:40:22    >         at java.base/java.lang.Thread.run(Thread.java:833)
03:40:22   2> NOTE: reproduce with: gradlew test --tests TestShapeDocValues.testXYPolygonCentroid -Dtests.seed=29AE25A2D4FB94F9 -Dtests.locale=en-SI -Dtests.timezone=SystemV/EST5 -Dtests.asserts=true -Dtests.file.encoding=UTF-8
03:40:22   2> NOTE: test params are: codec=Asserting(Lucene94), sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=en-SI, timezone=SystemV/EST5
03:40:22   2> NOTE: Linux 5.15.0-1018-gcp amd64/Oracle Corporation 17.0.2 (64-bit)/cpus=32,threads=1,free=258117120,total=270532608
03:40:22   2> NOTE: All tests run in this JVM: [TestCharArrayMap, TestBytesRefAttImpl, TestLZ4WithPresetDictCompressionMode, TestLucene90SegmentInfoFormat, TestPerFieldPostingsFormat, TestInetAddressPoint, TestLatLonPointDistanceFeatureQuery, TestShapeDocValues]
```

**Comment by jpountz** [comment]
@nknize I'm still seeing this failure once in a while, which seems to be related to a change of yours that I don't fully understand. Would you be able to look?

**Comment by ioanatia** [comment]
the test fails because right from the start the random generated polygon is invalid:

https://github.com/apache/lucene/blob/5acca826330b2afc15b6a2d5e2134d7d1a64e4a9/lucene/core/src/test/org/apache/lucene/document/TestShapeDocValues.java#L89

we can modify `BaseXYShapeTestCase.ShapeType.POLYGON.nextShape()` to always return a polygon that would not fail the  self intersections check:

https://github.com/apache/lucene/blob/5acca826330b2afc15b6a2d5e2134d7d1a64e4a9/lucene/core/src/test/org/apache/lucene/document/BaseXYShapeTestCase.java#L229

if we change `random().nextBoolean()` to `true` - the test succeeds when it's run with the same seed like in the PR description.
it looks like this is a safe change since `POLYGON.nextShape()` has limited usage.

**Comment by ioanatia** [comment]
@jpountz unless there have been more occurrences after https://github.com/apache/lucene/pull/12124 was merged, could this issue be closed?

**Comment by nknize** [comment]
I wasn't getting notifications on this for some reason, so thanks for stepping in @ioanatia!

Closing this issue for now and will re-open if we see another failure.
