### ISSUE TITLE
TestDocumentsWriterStallControl takes over a minute with -Ptests.seed=B83F4990EF501F47

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#11887]
### Description

```
gradlew test -p lucene/core --tests *TestDocumentsWriterStallControl* -Ptests.seed=B83F4990EF501F47
```

I noticed this while running unrelated tests but it does reproduce. Could be an unfortunate randomization pattern but it takes an awful long time to finish (and CPU usage is nearly nothing in between). Weird.

**Comment by rmuir** [comment]
this test is slower for me quite often as well, tends to take around entire minute in many cases.

**Comment by rmuir** [comment]
I don't think profiler is helpful because test is not doing anything, except sleeping on `Object.wait`. I used `jstack` while the test was hung:

```
"TEST-TestDocumentsWriterStallControl.testRandom-seed#[B83F4990EF501F47]" #20 prio=5 os_prio=0 cpu=118.76ms elapsed=100.21s tid=0x00007fff9405cc50 nid=0x37b3 in Object.wait()  [0x00007fffb5ffd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.5/Native Method)
	- waiting on <no object reference available>
	at java.lang.Thread.join(java.base@17.0.5/Thread.java:1304)
	- locked <0x00000000fcbdeee0> (a org.apache.lucene.index.TestDocumentsWriterStallControl$1)
	at java.lang.Thread.join(java.base@17.0.5/Thread.java:1372)
	at org.apache.lucene.index.TestDocumentsWriterStallControl.join(TestDocumentsWriterStallControl.java:313)
	at org.apache.lucene.index.TestDocumentsWriterStallControl.testRandom(TestDocumentsWriterStallControl.java:89)
```

**Comment by rmuir** [comment]
It runs much faster with this patch:
```
--- a/lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterStallControl.java
+++ b/lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterStallControl.java
@@ -62,7 +62,7 @@ public class TestDocumentsWriterStallControl extends LuceneTestCase {
             @Override
             public void run() {

-              int iters = atLeast(1000);
+              int iters = atLeast(100);
               for (int j = 0; j < iters; j++) {
                 ctrl.updateStalled(random().nextInt(stallProbability) == 0);
                 if (random().nextInt(5) == 0) { // thread 0 only updates
```

**Comment by rmuir** [comment]
The condition where this test takes minutes isn't that rare, I ran the test 10 times and hit the slow condition 3 out of 10 executions:
* 151s
* 158s
* 32s

With the patch, I ran the test 50 times and it was always reasonable. Will make a PR
