### ISSUE TITLE
org.apache.lucene.search.TestKnnFloatVectorQuery.testDocAndScoreQueryBasics fails reproducibly

### ISSUE THREAD

**Issue by cpoerschke** [apache/lucene#12181]
### Description

Please see e.g. https://lists.apache.org/thread/wz00z6gz18bbmkqtghkjtdqlokq3fx7p for full details.

```
Error Message:
java.lang.IllegalStateException: This DocAndScore query was created by a different reader

Stack Trace:
java.lang.IllegalStateException: This DocAndScore query was created by a different reader
at __randomizedtesting.SeedInfo.seed([D2B504855ECC5807:C35303238DC068AA]:0)
at org.apache.lucene.search.AbstractKnnVectorQuery$DocAndScoreQuery.createWeight(AbstractKnnVectorQuery.java:301)
at org.apache.lucene.search.TestKnnFloatVectorQuery.testDocAndScoreQueryBasics(TestKnnFloatVectorQuery.java:209)
...
```

### Gradle command to reproduce

./gradlew test --tests TestKnnFloatVectorQuery.testDocAndScoreQueryBasics -Dtests.seed=D2B504855ECC5807 -Dtests.multiplier=2 -Dtests.locale=ca-ES-VALENCIA -Dtests.timezone=Europe/Vienna -Dtests.asserts=true -Dtests.file.encoding=UTF-8

**Comment by cpoerschke** [comment]
I think this is a false-positive i.e. a test issue, pull request to follow.

**Comment by cpoerschke** [comment]
Manual issue closing - https://github.com/apache/lucene/commit/3bd06b1cb94fe8ca9e198463a7e1b9dc68316fa3 for `main` and https://github.com/apache/lucene/commit/caf55e0e798674715c775d5d1ff9138424a71307 for `branch_9x` - not sure why the first commit did not auto-close this issue.
