### ISSUE TITLE
Multiple ClassNotFoundExceptions in IntelliJ Fat Jar on ARM64 Java 20

### ISSUE THREAD

**Issue by contrebande-labs** [apache/lucene#12307]
### Description

We use IntelliJ to build a fat jar to run on ARM64 cloud VMs with Java 20 on Oracle Linux 8.5 to build Lucene BM25+HNSW indices.

Our first run gave us this error message that we fixed by manually extracting `lucene-core-9.6.0.jar/META-INF/versions/20/` in the classpath:

```
java.lang.LinkageError: MemorySegmentIndexInputProvider is missing in Lucene JAR file
	at org.apache.lucene.store.MMapDirectory.lookupProvider(MMapDirectory.java:437)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.apache.lucene.store.MMapDirectory.doPrivileged(MMapDirectory.java:395)
	at org.apache.lucene.store.MMapDirectory.<clinit>(MMapDirectory.java:448)
	at com.example.vertx.oci.lucene.LuceneHNSWIndexVerticle.lambda$initIndex$12(LuceneHNSWIndexVerticle.java:325)
	at io.vertx.lang.rx.DelegatingHandler.handle(DelegatingHandler.java:20)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.store.MemorySegmentIndexInputProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:496)
	at java.base/java.lang.Class.forName(Class.java:475)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:2785)
	at org.apache.lucene.store.MMapDirectory.lookupProvider(MMapDirectory.java:422)
	... 13 more
```

But then, 237GB RAM, 35 million documents and 2hrs20mins later, we got the following and couldn't find how to fix it since `org.apache.lucene.codecs.lucene90.Lucene90PostingsFormat` is already in the classpath:

```
Exception in thread "Lucene Merge Thread #0" org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene90' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [completion, Completion84, Completion90]
	at org.apache.lucene.index.ConcurrentMergeScheduler.handleMergeException(ConcurrentMergeScheduler.java:735)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:727)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene90' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [completion, Completion84, Completion90]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:111)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.<init>(PerFieldPostingsFormat.java:325)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat.fieldsProducer(PerFieldPostingsFormat.java:392)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:118)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:92)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:180)
	at org.apache.lucene.index.ReadersAndUpdates.getReaderForMerge(ReadersAndUpdates.java:788)
	at org.apache.lucene.index.IndexWriter.lambda$mergeMiddle$21(IndexWriter.java:5079)
	at org.apache.lucene.index.MergePolicy$OneMerge.initMergeReaders(MergePolicy.java:444)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5075)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4680)
	at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6432)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:639)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:700)
com.example.vertx.oci.lucene.exception.IndexDocumentException: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at com.example.vertx.oci.lucene.LuceneHNSWIndexVerticle.lambda$indexDocument$10(LuceneHNSWIndexVerticle.java:277)
	at io.vertx.lang.rx.DelegatingHandler.handle(DelegatingHandler.java:20)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:908)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:921)
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1529)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1817)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1470)
	at com.example.vertx.oci.lucene.LuceneHNSWIndexVerticle.lambda$indexDocument$10(LuceneHNSWIndexVerticle.java:271)
	... 9 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene90' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [completion, Completion84, Completion90]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:111)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.<init>(PerFieldPostingsFormat.java:325)
	at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat.fieldsProducer(PerFieldPostingsFormat.java:392)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:118)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:92)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:180)
	at org.apache.lucene.index.ReadersAndUpdates.getReaderForMerge(ReadersAndUpdates.java:788)
	at org.apache.lucene.index.IndexWriter.lambda$mergeMiddle$21(IndexWriter.java:5079)
	at org.apache.lucene.index.MergePolicy$OneMerge.initMergeReaders(MergePolicy.java:444)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5075)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4680)
	at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6432)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:639)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:700)

```

Anyone knows how to fix this, especially on the second without a solution? We think they are related but can't say for sure.

Thanks.

**Comment by uschindler** [comment]
The problem is that you FAT JAR file does not have all MR-JAR classes. `META-INF/versions/*` is missing (this causes the ClassNotFoundExceptions).
To load codecs also the Service Provider Files (SPI) need to be in `META_INF/services`. Important when you shade many JAR files you need to *merge* those descriptors.

**Comment by contrebande-labs** [comment]
I just hoped I could make a very common use case work with Lucene...

**Comment by uschindler** [comment]
> @uschindler If fat JARs are not supported or recommended with Lucene, what _is_ the recommended way to deploy a project incorporating Lucene? I cannot find any resources on this topic in Lucene's documentation. Is there an example deployment which users can be directed to?

If you want to create Fat JARs, you need to make sure that the following is correctly included:
- All classes in `META-INF/versions/**`
- All service provider files need to be merged (this is important if you inlcude multiple JAR files from Lucene into one. If you do not do this it will complain about missing codecs, depending on which order the Fat JAR was packaged.

If you use Maven, you can use the Maven Shade plugin with the following configuration (log4j2 is affected by the same problems): https://stackoverflow.com/questions/53049346/is-log4j2-compatible-with-java-11/54713830#54713830

See also official Maven Shade plugin documentation about ResourceTransformers (https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html) and also check this issue (https://issues.apache.org/jira/browse/MSHADE-385). You also need to pass the Manifest option "Multi-Release: true", otherwise Java won't detect your Fat JAR as containing multiple classfile versions.

Finally, as Fat JARs are incompatible with The Java Module System, we do not recommend to package Fat JARs. To deploy applications use the Java module system with named modules and put them into the module-path when running Java. This can also be done by crafting correct Manifest options.

**Comment by uschindler** [comment]
If you want to create a classical classpath application that can be started with `java -jar application.jar` the correct way is to *NOT* package everything into a fat `application.jar` and instead collect all output files next to the `application.jar`, which itsself has a MANIFEST like this:

```
Main-Class: my.app.Main
Class-Path: lucene-core-9.8.0.jar lucene-codecs-9.8.0.jar other-library.jar log4j-2.19.0.jar
```

When you then execute it, the `Class-Path` manifest entry will find the required JAR files in the same folder as the main JAR. This manifest entry can be easily created with Gradle assemble plugin. I don't know about Maven.

**Comment by davido** [comment]
@uschindler

We are using [Bazel](https://bazel.build) build system, and merging the two JARs like this:


# Merge jars so
# META-INF/services/org.apache.lucene.codecs.Codec
# contains the union of both Codec collections.
java_binary(
    name = "lucene-core-and-backward-codecs-merged",
    data = ["//lib:LICENSE-Apache2.0"],
    main_class = "NotImportant",
    runtime_deps = [
        # in case of conflict, we want the implementation of backwards-codecs
        # first.
        "@backward-codecs//jar",
        "@lucene-core//jar",
    ],
)

java_import(
    name = "lucene-core-and-backward-codecs",
    jars = [
        ":lucene-core-and-backward-codecs-merged_deploy.jar",
    ],
)

And it works with JDk11 and JDK17 as expected, but is failing on JDK21:

7) offlineReindexForAllAvailableIndicesIsPossibleInSlaveMode(com.google.gerrit.acceptance.pgm.LuceneReindexIT)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.store.MMapDirectory
	at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:161)
	at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:156)
	at com.google.gerrit.lucene.LuceneAccountIndex.dir(LuceneAccountIndex.java:91)
	at com.google.gerrit.lucene.LuceneAccountIndex.<init>(LuceneAccountIndex.java:105)
	at com.google.gerrit.lucene.LuceneAccountIndex$$FastClassByGuice$$416172e5.GUICE$TRAMPOLINE(<generated>)
	at com.google.gerrit.lucene.LuceneAccountIndex$$FastClassByGuice$$416172e5.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:907)
	at jdk.proxy2/jdk.proxy2.$Proxy59.create(Unknown Source)
	at com.google.gerrit.server.index.SingleVersionModule$SingleVersionListener.start(SingleVersionModule.java:98)
	at com.google.gerrit.server.index.SingleVersionModule$SingleVersionListener.start(SingleVersionModule.java:79)
	at com.google.gerrit.pgm.init.index.IndexManagerOnInit.start(IndexManagerOnInit.java:40)
	at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:121)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:62)
	at com.google.gerrit.acceptance.GerritServer.init(GerritServer.java:344)
	at com.google.gerrit.acceptance.StandaloneSiteTest.beforeTest(StandaloneSiteTest.java:140)
	at com.google.gerrit.acceptance.StandaloneSiteTest$1.evaluate(StandaloneSiteTest.java:117)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.LinkageError: MemorySegmentIndexInputProvider is missing in Lucene JAR file [in thread "main"]
	at org.apache.lucene.store.MMapDirectory.lookupProvider(MMapDirectory.java:437)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.apache.lucene.store.MMapDirectory.doPrivileged(MMapDirectory.java:395)
	at org.apache.lucene.store.MMapDirectory.<clinit>(MMapDirectory.java:448)
	... 54 more

So that this change, that is only bumping default Java level from JDK 17 to JDK 21 failing tests: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/387837

**Comment by davido** [comment]
@uschindler 

Thank you for clarifying and for the links to the specifications.

What confused me, is that the problem showed up after two changes: using JDK 21 at runtime, and updating to Lucene 9.8.0.

Apparently, starting from Lucene 9.x the Multi-Release JAR files are used:

```bash
davido@wizball:~/projects/gerrit/junk/WEB-INF/lib (jdk_21_support %)$ unzip -t lucene-core-9.8.0.jar | grep MemorySegmentIndexInputProvider
    testing: META-INF/versions/19/org/apache/lucene/store/MemorySegmentIndexInputProvider.class   OK
    testing: META-INF/versions/20/org/apache/lucene/store/MemorySegmentIndexInputProvider.class   OK
    testing: META-INF/versions/21/org/apache/lucene/store/MemorySegmentIndexInputProvider.class   OK
```

Clearly, because Bazel currently doesn't have MR-JAR support: [1], trying to merge `lucene-core.jar` and `lucene-backward-codecs.jar` is breaking MR-JAR format, that explains `NoClassDefFoundError` we are seeing.

Gerrit Code Review project started to merge `lucene-core` and `backward-codecs` 8 years ago to "understand" index format created by older Lucene releases, so that Gerrit site could be reindexed with new Gerrit releases that is shipping new Lucene version, with this explanation in the commit message:

```
Merge Lucene core and backward-codecs jars

Both of these jars provide a provider-configuration file in
META-INF/services/org.apache.lucene.codecs.Codec registering their
respective implementations as providers of this codec. The proper way
to merge these files is to concatenate them, but the normal Buck build
process would otherwise choose one arbitrarily.

Add a new custom rule merge_maven_jars to merge multiple Maven jars
together using a simple Python script. The script concatenates all the
entries in two zip files, preferring the entry found in the first file
on the command line, which is still arbitrary but at least
deterministic. It specially handles files in the META-INF/services
directory by concatenating them.

Use this new rule to merge the old :core and :backward-codecs rules
into a single :core-and-backward-codecs rule.
```

In fact, it's still true for Lucene 9.8.0, where:

lucene-backward-codecs/META-INF/services/org.apache.lucene.codecs.Codec
```
org.apache.lucene.backward_codecs.lucene80.Lucene80Codec
org.apache.lucene.backward_codecs.lucene84.Lucene84Codec
org.apache.lucene.backward_codecs.lucene86.Lucene86Codec
org.apache.lucene.backward_codecs.lucene87.Lucene87Codec
org.apache.lucene.backward_codecs.lucene70.Lucene70Codec
org.apache.lucene.backward_codecs.lucene90.Lucene90Codec
org.apache.lucene.backward_codecs.lucene91.Lucene91Codec
org.apache.lucene.backward_codecs.lucene92.Lucene92Codec
org.apache.lucene.backward_codecs.lucene94.Lucene94Codec
```

and

lucene-core/META-INF/services/org.apache.lucene.codecs.Codec
```
org.apache.lucene.codecs.lucene95.Lucene95Codec
```

However, the better question is: why those file need to be merged? To not mess around with MR-JAR file format, wouldn't it e sufficient to just put the `lucene-backward-codecs` and `lucene-core` AS-IS on the classpath?

So, I stopped merging the JARs, and preserved the original JARs. Now, the tests are passing, and I was able to reindex gerrit site with latest Lucene release 9.8.0 that was created with previous Lucene release 8.11.2:

```
  $ davido@wizball:~/projects/gerrit (jdk_21_support %)$ unzip -t bazel-bin/gerrit.war | grep lucene | grep 9.8.0
    testing: WEB-INF/lib/lucene-core-9.8.0.jar   OK
    testing: WEB-INF/lib/lucene-backward-codecs-9.8.0.jar   OK
    testing: WEB-INF/lib/lucene-queryparser-9.8.0.jar   OK
    testing: WEB-INF/lib/lucene-analysis-common-9.8.0.jar   OK
    testing: WEB-INF/lib/lucene-misc-9.8.0.jar   OK
```

Am I understanding correctly, that with the recent Lucene releases, the merging of `lucene-backward-codecs` and `lucene-core` JARs is not necessary any more?

[1] https://github.com/bazelbuild/bazel/issues/5947
[2] https://gerrit-review.googlesource.com/c/gerrit/+/69850

**Comment by uschindler** [comment]
There is no need to merge those files and as said before this is discouraged. It was never required. I have no idea why they did this. It is and was broken from the beginning.

The jar files just need both be next to each other on classpath or the main modular project needs to depend on both modules. Important: all must be in same class loader.

I have no idea why they did this back at that time. The explanation above just explains how to merge, but it doesn't explain why they did this.

**Comment by uschindler** [comment]
FYI, one reason why they might have done this: if the whole thing is a webapp, with wrong setup or broken containers the class loading is often broken, especially if somebody drops jar files also into the main classpath. Normally a separate classloader should be used solely for the webapp. It should then work, unless in some broken containers where SPI (ServiceLoader) does not work.
Jetty is known to work fine (see e.g., Apache Solr) and Tomcat should behave correctly, too (unverified).

**Comment by uschindler** [comment]
> Apparently, starting from Lucene 9.x the Multi-Release JAR files are used:

Actually, Lucene already used in its 8.x releases the MRJAR features, but without the extra class files it was just not perfectly optimized when runtime was Java 9+.

The new features of Java 19+ like improved mmap disk IO and vectorization are enabled without a fallback, so this causes havoc if the class files are not found.
