### ISSUE TITLE
Can backward reading be less adversarial to BufferedIndexInput?

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#12356]
### Description

Forked from https://lists.apache.org/thread/1fskhmz84pp60o41txsxj2193vt9txod: if `BufferedIndexInput` is asked to read N bytes backward, one after the other, it will internally trigger N refills of its internal 1kB buffer. While this particular case may be better fixed by changing the layout of the data (#12355), there are a couple other cases when we occasionally need to go backwards and it would be nice if BufferedIndexInput handled it more gracefully (e.g. when navigating to a parent node in the BKD index)?

**Comment by jpountz** [comment]
I reviewed some of the other places that we have that may read backwards:
 - The BKD index may jump backwards when moving from a node to the parent node, but then reading information about this parent node involves forward reads, and moving to a child node would translate into a forward read as well.
 - The stored fields and term vectors indexes perform binary searches on RandomAccessIndexInput, so there are occasional backward reads as well.

I'm expecting this issue to raise the question of whether it's actually a good idea to read the terms index (and BKD index, and stored fields index, and term vectors index) off-heap, or if we should load it in heap like we used to in the past. As far as I'm concerned, I'd really like to keep loading it off-heap by default, this change has simplified many things, e.g. we no longer have RAM accounting on our readers, we almost don't need to take data size into account for sizing the JVM heap, etc.

@romseygeek I worry that the assumption that observing one backward read means that the next one is likely going to be backward too might be too strong, e.g. we'd have the same issue that every read needs to perform a refill if backward and forward reads are interleaved, which could happen as part of the binary search for instance. Maybe we could meet half way instead and set bufferStart so that `pos` is in the middle of the buffer when refilling due to a backward read?

**Comment by romseygeek** [comment]
> we'd have the same issue that every read needs to perform a refill if backward and forward reads are interleaved

I think this would only be the case if the target of the binary search was precisely on the boundary of the buffer pages?  Which could happen with whatever paging strategy we use.

**Comment by rahulgoswami** [comment]
Based on the idea that @romseygeek proposed above, I tried the below change in readByte(log pos). It works sometimes, but testing on a 5 million+ dataset I get a CorruptIndexException some time into the indexing. Not sure why that should happen, and only after making this change. Thoughts ?

  @Override
  public final byte readByte(long pos) throws IOException {
    long index = pos - bufferStart;
    if (index < 0 || index >= buffer.limit()) {
      if(index<0) {
        bufferStart=Math.min(pos, (bufferStart-bufferSize) < 0 ? 0:(bufferStart-bufferSize));
      }else {
        bufferStart = pos;
      }
      buffer.limit(0);  // trigger refill() on read
      seekInternal(pos);
      refill();
      index = 0;
    }
    return buffer.get((int) index);
  }


Exception:
2023-06-08 03:14:58.040 ERROR (qtp391506011-24) [   x:techproducts] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Server error writing document id c55ea05bded8d478d1942535f30c5791001 to the index => org.apache.solr.common.SolrException: Server error writing document id c55ea05bded8d478d1942535f30c5791001 to the index
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:246)
org.apache.solr.common.SolrException: Server error writing document id c55ea05bded8d478d1942535f30c5791001 to the index
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:246) ~[?:?]
.....
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:886) ~[?:?]
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:900) ~[?:?]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1477) ~[?:?]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1473) ~[?:?]
	at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:973) ~[?:?]
	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:342) ~[?:?]
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:294) ~[?:?]
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241) ~[?:?]
	... 68 more
Caused by: org.apache.lucene.index.CorruptIndexException: invalid state: base=0, docID=93773 (resource=SimpleFSIndexInput(path="C:\Work\Solr\solr-8.11.1\example\techproducts\solr\techproducts\data\index\_13xx.fdt"))
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.copyChunks(CompressingStoredFieldsWriter.java:560) ~[?:?]
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.merge(CompressingStoredFieldsWriter.java:633) ~[?:?]
	at org.apache.lucene.index.SegmentMerger.mergeFields(SegmentMerger.java:228) ~[?:?]
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:105) ~[?:?]
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4788) ~[?:?]
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4392) ~[?:?]
	at org.apache.solr.update.SolrIndexWriter.merge(SolrIndexWriter.java:201) ~[?:?]
	at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:5951) ~[?:?]
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:626) ~[?:?]
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:684) ~[?:?]

**Comment by mikemccand** [comment]
Could we improve `IOContext` to let the `Directory` impl know that we may read backwards, or more "random accessy"?  We seem to know the few places in Lucene's sources where we do this (thanks @jpountz).

**Comment by jpountz** [comment]
We added `IOContext#load` for this purpose recently (#11930), it tells the directory that the index input is going to be hot and accessed in a random fashion. We use it for the terms, points, stored fields and term vectors indexes.

**Comment by jpountz** [comment]
One thing worth noting is that Alan's change only modifies the behavior when reading index files via the `RandomAccessInput` interface. If you read a file via the `IndexInput` abstraction, the behavior doesn't change.
