### ISSUE TITLE
Why is the test-framework trying to write files in /tmp?

### ISSUE THREAD

**Issue by msokolov** [apache/lucene#12386]
### Description

This test line reproduces for me:

    ./gradlew :lucene:replicator:test -Ptests.nightly=true --tests TestNRTReplication.testReplicateDeleteAllDocuments

It fails with

```
org.apache.lucene.replicator.nrt.TestNRTReplication > testReplicateDeleteAllDocuments FAILED                                                                  
    java.lang.RuntimeException: replica R0 failed to start                                                                                                    
        at __randomizedtesting.SeedInfo.seed([4606DB559DC17BCF:3ED572AE6AC99E12]:0)                                                                           
        at org.apache.lucene.replicator.nrt.TestNRTReplication.startNode(TestNRTReplication.java:145)                                                         
        at org.apache.lucene.replicator.nrt.TestNRTReplication.testReplicateDeleteAllDocuments(TestNRTReplication.java:239)                                   
```

and in the test output you can see that the test framework is trying to create `/tmp`??

I suspect this has to do with the fact that I have symlinked  `/tmp` -> `/local/tmp`. But why would we ever write anything in `/tmp`? I believe we use a local tmp directory in the build dir, don't we? Also tried setting `java.io.tmpdir` but it didn't seem to make any difference.

```
 1> 0.662s       :     parent  There was 1 failure:
  1> 0.662s       :     parent  1) org.apache.lucene.replicator.nrt.TestSimpleServer
  1> 0.665s       :     parent  java.nio.file.FileAlreadyExistsException: /tmp
  1> 0.665s       :     parent         at __randomizedtesting.SeedInfo.seed([23C52DD9AA2B6CD]:0)
  1> 0.665s       :     parent         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
  1> 0.665s       :     parent         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
  1> 0.665s       :     parent         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
  1> 0.666s       :     parent         at java.base/sun.nio.fs.UnixFileSystem
Provider.createDirectory(UnixFileSystemProvider.java:389)
  1> 0.666s       :     parent         at org.apache.lucene.test_framework@9.
7.0-SNAPSHOT/org.apache.lucene.tests.mockfile.FilterFileSystemProvider.createDirectory(FilterFileSystemProvider.java:129)                                       1> 0.666s       :     parent         at org.apache.lucene.test_framework@9.
7.0-SNAPSHOT/org.apache.lucene.tests.mockfile.FilterFileSystemProvider.createDirectory(FilterFileSystemProvider.java:129)
  1> 0.666s       :     parent         at org.apache.lucene.test_framework@9.
  1> 0.666s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.mockfile.FilterFileSystemProvider.createDirectory(FilterFileSystemProvider.java:129)
  1> 0.667s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.mockfile.FilterFileSystemProvider.createDirectory(FilterFileSystemProvider.java:129)
  1> 0.667s       :     parent         at org.apache.lucene.test_framework@9.
7.0-SNAPSHOT/org.apache.lucene.tests.mockfile.FilterFileSystemProvider.createDirectory(FilterFileSystemProvider.java:129)
  1> 0.667s       :     parent         at org.apache.lucene.test_framework@9.
7.0-SNAPSHOT/org.apache.lucene.tests.mockfile.ExtrasFS.createDirectory(ExtrasFS.java:57)
  1> 0.667s       :     parent         at java.base/java.nio.file.Files.createDirectory(Files.java:690)
  1> 0.667s       :     parent         at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
  1> 0.668s       :     parent         at java.base/java.nio.file.Files.createDirectories(Files.java:743)
  1> 0.668s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.initializeJavaTempDir(TestRuleTemporaryFilesCleanup.java:181)
  1> 0.668s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.before(TestRuleTemporaryFilesCleanup.java:102)
  1> 0.668s       :     parent         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.before(TestRuleAdapter.java:26)
  1> 0.668s       :     parent         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:35)
  1> 0.669s       :     parent         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)                                                                        1> 0.669s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)                                             1> 0.669s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  1> 0.669s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  1> 0.669s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  1> 0.670s       :     parent         at org.apache.lucene.test_framework@9.7.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  1> 0.670s       :     parent         at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
  1> 0.670s       :     parent         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 0.670s       :     parent         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  1> 0.670s       :     parent         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  1> 0.671s       :     parent         at java.base/java.lang.Thread.run(Thread.java:829)
  1> 0.671s       :     parent
  1> 0.671s       :     parent  FAILURES!!!
  1> 0.671s       :     parent  Tests run: 0,  Failures: 1
```

**Comment by msokolov** [comment]
It seems the issue is that this (and other related) tests start another java process and it is *that* process that writes files in /tmp. I was able to fix by adding:

    cmd.add("-Djava.io.tmpdir=" + childTempDir.toFile());

to `TestNRTReplication.startNode`. I don't know these tests well (at all!) but this seems pretty safe to me? Would appreciate some eyes on it though that might know better

**Comment by uschindler** [comment]
This test was always special. It is not caused by the test framework, only this special test an how it executes a sub-process causes this.

This test has always caused issues, we should improve it. I think here this issue is caused by the symlink.

**Comment by msokolov** [comment]
Thanks @uschindler -- I posted my fix. My only question is whether this should be handled by `getJvmForkArguments()` but your comment makes me think we should just fix these tests and not try to make some more general patch

**Comment by msokolov** [comment]
See https://github.com/apache/lucene/pull/12387 (why doesn't this link itself here?)

**Comment by uschindler** [comment]
> See #12387 (why doesn't this link itself here?)

You need to say "this closes #12386" in the issue description. The title of the PR is not relevant to this.

**Comment by uschindler** [comment]
There may be more tests having same issue. You can grep through the source tree and find all ProcessBuilders. :-)

**Comment by uschindler** [comment]
> > See #12387 (why doesn't this link itself here?)
> 
> You need to say "this closes #12386" in the issue description. The title of the PR is not relevant to this.

I linked the PR to this issue manually. Please also not forget to add milestones to issue and pr.

**Comment by msokolov** [comment]
> There may be more tests having same issue. You can grep through the source tree and find all ProcessBuilders. :-)

I didn't see others fail when I ran the smoke-tester. And now I did grep and tried a few like TestStressLockFactories and TestIndexWriterOnJRECrash, and they seem to pass (even with tests.nightly=true)

**Comment by uschindler** [comment]
> > There may be more tests having same issue. You can grep through the source tree and find all ProcessBuilders. :-)
> 
> I didn't see others fail when I ran the smoke-tester. And now I did grep and tried a few like TestStressLockFactories and TestIndexWriterOnJRECrash, and they seem to pass (even with tests.nightly=true)

Those subprocesses don't create temporary files. Thanks for checking!
