### ISSUE TITLE
IndexWriter and ConcurrentMergeScheduler and SegmentReader can cause static initialization deadlock

### ISSUE THREAD

**Issue by xjtushilei** [apache/lucene#12419]
### Description

I use lucene 9.6 in multi-threading, and then found that if the three classes `IndexWriter`, `SegmentReader`, and `ConcurrentMergeScheduler` are used in a multi-threaded environment, the thread will be stuck. 

The reason is that the `TestSecrets.java` class caused static initialization deadlock.

This bug has a great impact on me, I hope it can be fixed as soon as possible.

The following code can be reproduced stably.

```
import org.apache.lucene.index.ConcurrentMergeScheduler;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.store.ByteBuffersDirectory;

import java.io.IOException;
import java.util.concurrent.CountDownLatch;

public class Test {

    public static void main(String[] args) throws InterruptedException {

        CountDownLatch startLatch = new CountDownLatch(1);

        Thread t1 = new Thread(() -> {
            try {
                startLatch.await();
                new IndexWriter(new ByteBuffersDirectory(), new IndexWriterConfig());
            } catch (IOException | InterruptedException e) {
                throw new RuntimeException(e);
            }
        });

        Thread t2 = new Thread(() -> {
            try {
                startLatch.await();
                new ConcurrentMergeScheduler();
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        });

        t1.start();
        t2.start();

        System.out.println("Start!");
        startLatch.countDown();

        t2.join();
        t1.join();

        System.out.println("Done");
    }
}
```

### Version and environment details

- Lucene version: 9.6
- Java version: 11, and the java version in my MacBookPro  is "11.0.16.1" 2022-08-18 LTS
- OS
  - mac os 11.6.1
  - centos 7.x

**Comment by tang-hi** [comment]
In my opinion, this deadlock only occurs at the beginning of program execution. As long as you ensure that the IndexWriter is constructed before the ConcurrentMergeScheduler, the deadlock situation should not occur.

Do you have a specific scenario where you need to concurrently construct the IndexWriter and ConcurrentMergeScheduler at the beginning of the program?
```Java
public static void main(String[] args) throws Exception {
    CountDownLatch startLatch = new CountDownLatch(1);

    Thread t1 = new Thread(() -> {
      try {
        new IndexWriter(new ByteBuffersDirectory(), new IndexWriterConfig());
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    });

    Thread t2 = new Thread(() -> {
      try {
        startLatch.await();
        new ConcurrentMergeScheduler();
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    });

    t1.start();
    t2.start();

    t1.join();
    System.out.println("Start!");
    startLatch.countDown();

    t2.join();

    System.out.println("Done");

    for(int i = 0; i < 1000; i++) {
      deadlock();
    }
  }

  static void deadlock() throws InterruptedException {
    CountDownLatch startLatch = new CountDownLatch(1);

    Thread t1 = new Thread(() -> {
      try {
        startLatch.await();
        new IndexWriter(new ByteBuffersDirectory(), new IndexWriterConfig());
      } catch (IOException | InterruptedException e) {
        throw new RuntimeException(e);
      }
    });

    Thread t2 = new Thread(() -> {
      try {
        startLatch.await();
        new ConcurrentMergeScheduler();
      } catch (InterruptedException e) {
        throw new RuntimeException(e);
      }
    });

    t1.start();
    t2.start();

    System.out.println("Start!");
    startLatch.countDown();

    t2.join();
    t1.join();

    System.out.println("Done");
  }

```

**Comment by hydrogen666** [comment]
@tang-hi Our Elasticsearch has migrated to Segment replication mechanism, so the code runing on the Primary shard and Replica shard is different. The replica shard will not construct `IndexWriter` any more.

Thread A starts a primary shard with procedure below
1. Construct `ConcurrentMergeScheduler`
2. Consctruct `IndexWriter`

Thread B start a replica shard with precedure below
1. Deserialize `SegmentInfos` from disk
2. Start a read-only SearcherManager

In the first step, we will call `SegmentInfos#readCommit` to  deserialize `SegmentInfos`, call stack below
```
at org.apache.lucene.index.IndexWriter.<clinit>(IndexWriter.java:6485)
at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:499)
at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:364)
at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:311)
```

**Comment by danmuzi** [comment]
@xjtushilei @tang-hi @hydrogen666 

Will be fixed in Lucene 10.5
PR : https://github.com/apache/lucene/pull/15864
