### ISSUE TITLE
Lucene KNN token vectors demo

### ISSUE THREAD

**Issue by bobmanc** [apache/lucene#12416]
### Description

0

I am trying to use a larger vector dictionary with the demo code. I have tried all the files here https://nlp.stanford.edu/projects/glove/ and every one throws this...

`inputs are added out of order lastInput=[74 68 65] vs input=[2e]
java.lang.AssertionError: inputs are added out of order lastInput=[74 68 65] vs input=[2e]
    at org.apache.lucene.util.fst.FSTCompiler.add(FSTCompiler.java:478)
    at com.trevr.service.lucene.knn.KnnVectorDict$Builder.addOneLine(KnnVectorDict.java:222)`

**Comment by msokolov** [comment]
Your dictionary must be sorted in UTF-8 order

**Comment by slow-J** [comment]
Would it make sense to change https://github.com/apache/lucene/blob/9cda46563a4bb30f26fd120ab9bc1397106bf945/lucene/core/src/java/org/apache/lucene/util/fst/FSTCompiler.java#L855 to say that: `inputs must be added in non-decreasing order`?

**Comment by msokolov** [comment]
+1 for adding some documentation. I guess that error message could be clearer, but could we also check to see if the demo code is documented since it might not be obvious what data is generating this error?
