### ISSUE TITLE
Reading after Segment Merge fails for HNSW

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#12570]
### Description

While testing with Lucene Util, I ran 50000 vectors through current main. To test merging, I decreased the rambuffersize to 128MB, indexed, and then force-merged.

When merging, It appears we are creating more than `M*2` neighbor connections.

I am still digging into the potential cause, but its been around since https://github.com/apache/lucene/commit/ef42af65f27f7f078b1ab426de9f2b2fa214ad86

I get this stack trace:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
	at org.apache.lucene.codecs.lucene95.Lucene95HnswVectorsReader$OffHeapHnswGraph.seek(Lucene95HnswVectorsReader.java:496)
	at org.apache.lucene.util.hnsw.HnswGraphSearcher.graphSeek(HnswGraphSearcher.java:448)
	at org.apache.lucene.util.hnsw.HnswGraphSearcher.searchLevel(HnswGraphSearcher.java:400)
	at org.apache.lucene.util.hnsw.HnswGraphSearcher.search(HnswGraphSearcher.java:274)
	at org.apache.lucene.util.hnsw.HnswGraphSearcher.search(HnswGraphSearcher.java:131)
	at org.apache.lucene.codecs.lucene95.Lucene95HnswVectorsReader.search(Lucene95HnswVectorsReader.java:277)
	at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsReader.search(PerFieldKnnVectorsFormat.java:276)
	at org.apache.lucene.index.CodecReader.searchNearestVectors(CodecReader.java:253)
	at org.apache.lucene.index.LeafReader.searchNearestVectors(LeafReader.java:258)
	at org.apache.lucene.search.KnnFloatVectorQuery.approximateSearch(KnnFloatVectorQuery.java:82)
	at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:131)
	at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:117)
	at org.apache.lucene.search.AbstractKnnVectorQuery.sequentialSearch(AbstractKnnVectorQuery.java:101)
	at org.apache.lucene.search.AbstractKnnVectorQuery.rewrite(AbstractKnnVectorQuery.java:86)
	at org.apache.lucene.search.KnnFloatVectorQuery.rewrite(KnnFloatVectorQuery.java:44)
	at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:755)
	at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:766)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:649)
	at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:485)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:500)
	at KnnGraphTester.doKnnVectorQuery(Unknown Source)
	at KnnGraphTester.testSearch(Unknown Source)
	at KnnGraphTester.run(Unknown Source)
	at KnnGraphTester.main(Unknown Source)
```

### Version and environment details

Lucene Main & Future 9.8.

**Comment by benwtrent** [comment]
OK, this bug has been around since 9.6. I tried to replicate in 9.5 and it didn't. 

So, I am guessing something around using an existing graph to merge ends up creating more connections than the expected maximum of `m*2`.

**Comment by benwtrent** [comment]
OK, debugging some more, looks like merging multiple segments and then force merging with Lucene Util 100% replicates this in 9.6.

The connection count on force merge increases from the configured 32 to 192. We need to limit the diverse connections and backwards connections I am guessing.

To protect users in the medium term, something like

```java
if (arcCount > currentNeighborsBuffer.length) {
  currentNeighborsBuffer = ArrayUtil.grow(currentNeighborsBuffer, arcCount);
}
```
should be added for Lucene95 codec vector reader. 


But we are expanding connections to a fairly obscene amount. Jumping from an initial connection configuration of 32 to a whopping 192 is crazy!

**Comment by jmazanec15** [comment]
Ill take a look too @benwtrent. 192 seems to be a lot. From a high level scan of the HNSWGraphBuilder, I do not see anything that obviously causes neighbors to go above M/2M. The 2 main points I see are:
1. [selecting neighbors](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java#L286-L295) 
2. [backwards connections](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java#L276-L279)

>  looks like merging multiple segments and then force merging

What did you mean by merging and then force merging? Do you have the luceneutil params you ran with for replication?

**Comment by benwtrent** [comment]
> What did you mean by merging and then force merging? Do you have the luceneutil params you ran with for replication?

I indexed 500000 cohere 768 vectors with a buffer of 128MB. This causes some flushes and the writer to do merging.

Then I have luceneutil do a forceMerge.

This reliably replicates the issue.

**Comment by benwtrent** [comment]
@jmazanec15 I just noticed something in my testing as a tripled checked everything.

`'maxConn': (96,),` was left over from a previous test. So, a max of 192 is perfectly fine. But, for some reason the index reader is losing this information or Lucene Util is not providing it. I am double checking Lucene Util as I haven't been able to replicate with a unit test.

**Comment by benwtrent** [comment]
🎉 
Its a bug in Lucene Util!

This patch works in the forceMerge() method.
```
    IndexWriterConfig iwc = new IndexWriterConfig().setOpenMode(IndexWriterConfig.OpenMode.APPEND);
    iwc.setCodec(
      new Lucene95Codec() {
        @Override
        public KnnVectorsFormat getKnnVectorsFormatForField(String field) {
          return new Lucene95HnswVectorsFormat(maxConn, beamWidth);
        }
      });
```

ForceMerge is not supplying the same Index Writer Config!

The question then becomes, is this a valid usecase? If not, I won't bother with my "fix". It does seem like a nice safety net. I don't know for sure if we really restrict the number of connections when adding back-connections :/

**Comment by jmazanec15** [comment]
Oh right I actually raised a PR sometime back around this but forgot about it: https://github.com/apache/lucene/pull/12002. 

> The question then becomes, is this a valid usecase? If not, I won't bother with my "fix". It does seem like a nice safety net. I don't know for sure if we really restrict the number of connections when adding back-connections :/

For valid use case, are you referring to dynamically changing M value for an index?

**Comment by benwtrent** [comment]
> For valid use case, are you referring to dynamically changing M value for an index?

Correct.

Or do we actually enforce these limits on the index writer to the point we are comfortable only ever allowing a maximum of `M*2`?

**Comment by jmazanec15** [comment]
For dynamically changing M, I would be a little hesitant IMO. It could lead to inconsistent behavior, where some segments are searched very fast and others slow. If we were to support it, I would say that the initialization from graph should not be used because this might hurt the integrity of the graph.

> I don't know for sure if we really restrict the number of connections when adding back-connections :/

Don't we limit back connections here: https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java#L276-L279?

**Comment by benwtrent** [comment]
Closing this issue. Discovered it was a user error via Lucene Util. 

Merged code to protect against this weirdness anyways.
