### ISSUE TITLE
Reproducible TestDrillSideways failure

### ISSUE THREAD

**Issue by iverase** [apache/lucene#12601]
### Description

The following gradle command fails reproducibly on main with the following error:

```
   >     java.lang.AssertionError
   >         at __randomizedtesting.SeedInfo.seed([CEBE5325E431003F:BCF2762A5551B64C]:0)
   >         at junit@4.13.1/org.junit.Assert.fail(Assert.java:87)
   >         at junit@4.13.1/org.junit.Assert.assertTrue(Assert.java:42)
   >         at junit@4.13.1/org.junit.Assert.assertTrue(Assert.java:53)
   >         at org.apache.lucene.facet.TestDrillSideways.verifyEquals(TestDrillSideways.java:1758)
   >         at org.apache.lucene.facet.TestDrillSideways.testRandom(TestDrillSideways.java:1324)
   >         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
   >         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)

```

### Gradle command to reproduce

```
./gradlew test --tests TestDrillSideways.testRandom -Dtests.seed=CEBE5325E431003F
```

**Comment by stefanvodita** [comment]
Reverting #921 fixes the test, so I think this is the same issue that @Yuti-G investigated in #12418.
I ran the test in verbose mode (`./gradlew test --tests TestDrillSideways.testRandom -Dtests.seed=CEBE5325E431003F -Dtests.verbose=true --max-workers=1`). Here's the info for the bit that's failing:

```
  1> TEST: iter=4 baseQuery=b numDrillDown=1 useSortedSetDV=true
  1>   dim3=[[e2 a1 9b e2 a2 b8 e2 a0 a1 e2 a1 97 e2 a1 a1 e2 a0 b4 e2 a2 91 e2 a1 98 e2 a3 9e e2 a1 97 e2 a0 ab e2 a2 80 e2 a1 a0 e2 a0 86 e2 a0 9a]]
  1>   compute expected
  1>     exp: id=2 is a near-miss on dim=3
  1>   verify all facets
  1>   verify totHits=0
  1>     dim0 topN=2 (vs 2 unique values)
  1>       actual
  1>       expected (unsorted)
  1>     dim1 topN=3 (vs 4 unique values)
  1>       actual
  1>       expected (sorted)
  1>       topN=3 expectedTopN=0
  1>     dim2 topN=6 (vs 8 unique values)
  1>       actual
  1>       expected (sorted)
  1>       topN=6 expectedTopN=0
  1>     dim3 topN=16 (vs 16 unique values)
  1>       actual
  1>         0: [c7 9c c7 a7 c7 be c6 ae]: 1
  1>         1: [ea a5 a4 ea a5 ac ea a5 a8 ea a5 af ea a5 ac ea a5 b1]: 1
  1>       expected (unsorted)
  1>         0: [c7 9c c7 a7 c7 be c6 ae]: 1
  1>         1: [f0 90 92 84]: 1
```

**Comment by benwtrent** [comment]
closing as duplicate to https://github.com/apache/lucene/issues/12418
