### ISSUE TITLE
xml.TestCoreParser#testSpanNearQueryWithoutSlopXML fails because of changed exception message

### ISSUE THREAD

**Issue by uschindler** [apache/lucene#12708]
### Description

The test `org.apache.lucene.queryparser.xml.TestCoreParser#testSpanNearQueryWithoutSlopXML` fails in Java 22 EA builds:

```
org.junit.ComparisonFailure: expected:<...berFormatException: [For input string: ""]> but was:<...berFormatException: []>
	at __randomizedtesting.SeedInfo.seed([50F854467969E2C3:7F8CC4BC3195F1BF]:0)
	at [junit@4.13.1/org.junit.Assert.assertEquals](mailto:junit@4.13.1/org.junit.Assert.assertEquals)(Assert.java:117)
	at [junit@4.13.1/org.junit.Assert.assertEquals](mailto:junit@4.13.1/org.junit.Assert.assertEquals)(Assert.java:146)
	at org.apache.lucene.queryparser.xml.TestCoreParser.testSpanNearQueryWithoutSlopXML(TestCoreParser.java:165)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke)(RandomizedRunner.java:1758)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate)(RandomizedRunner.java:946)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate)(RandomizedRunner.java:982)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate)(RandomizedRunner.java:996)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate)(TestRuleSetupTeardownChained.java:48)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate)(AbstractBeforeAfterRule.java:43)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate)(TestRuleThreadAndTestName.java:45)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate)(TestRuleIgnoreAfterMaxFailures.java:60)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate)(TestRuleMarkFailure.java:44)
	at [junit@4.13.1/org.junit.rules.RunRules.evaluate](mailto:junit@4.13.1/org.junit.rules.RunRules.evaluate)(RunRules.java:20)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate)(StatementAdapter.java:36)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run)(ThreadLeakControl.java:390)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask)(ThreadLeakControl.java:843)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate)(ThreadLeakControl.java:490)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest)(RandomizedRunner.java:955)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate)(RandomizedRunner.java:840)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate)(RandomizedRunner.java:891)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate)(RandomizedRunner.java:902)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate)(AbstractBeforeAfterRule.java:43)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate)(StatementAdapter.java:36)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate)(TestRuleStoreClassName.java:38)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate)(NoShadowingOrOverridesOnMethodsRule.java:40)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate)(NoShadowingOrOverridesOnMethodsRule.java:40)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate)(StatementAdapter.java:36)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate)(StatementAdapter.java:36)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate)(TestRuleAssertionsRequired.java:53)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate)(AbstractBeforeAfterRule.java:43)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate)(TestRuleMarkFailure.java:44)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate)(TestRuleIgnoreAfterMaxFailures.java:60)
	at [org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate](mailto:org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate)(TestRuleIgnoreTestSuites.java:47)
	at [junit@4.13.1/org.junit.rules.RunRules.evaluate](mailto:junit@4.13.1/org.junit.rules.RunRules.evaluate)(RunRules.java:20)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate)(StatementAdapter.java:36)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run)(ThreadLeakControl.java:390)
	at [randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0](mailto:randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0)(ThreadLeakControl.java:850)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

This happens because the Exception message on `Integer.parseInt("")` (empty string arg) now has a different error message. The test relies on the message. This should generally be avoided, but I will open a bug report in the openjdk bug tracker about this:

```
$ ./jdk-17.0.2/bin/jshell
|  Welcome to JShell -- Version 17.0.2
|  For an introduction type: /help intro

jshell> Integer.parseInt("");
|  Exception java.lang.NumberFormatException: For input string: ""
|        at NumberFormatException.forInputString (NumberFormatException.java:67)
|        at Integer.parseInt (Integer.java:678)
|        at Integer.parseInt (Integer.java:786)
|        at (#1:1)

$ ./jdk-22/bin/jshell
|  Willkommen bei JShell - Version 22-ea
|  Geben Sie für eine Einführung Folgendes ein: /help intro

jshell> Integer.parseInt("");
|  Ausnahme java.lang.NumberFormatException:
|        at Integer.parseInt (Integer.java:565)
|        at Integer.parseInt (Integer.java:685)
|        at (#1:1)
```

**Comment by uschindler** [comment]
It only affect the empty String.

**Comment by uschindler** [comment]
See the issue in openjdk: https://bugs.openjdk.org/browse/JDK-8318646

**Comment by uschindler** [comment]
I will update JDK tomorrow or Friday and the issue should be gone.

**Comment by uschindler** [comment]
Hi, JDK-22 EA was updated to build 21, which contains fix for https://bugs.openjdk.org/browse/JDK-8318646

**Comment by uschindler** [comment]
I still think we should improve the test like als stated by openjdk people. The exception mesage is not part of the sepc so you should not rely with tests on its message. This may also cause issues once those are localized.

**Comment by vigyasharma** [comment]
Made a small change to assert on the exception type instead of checking the exception message string.
