### ISSUE TITLE
Reproducible failure in TestIndexWriter.testHasUncommittedChanges

### ISSUE THREAD

**Issue by easyice** [apache/lucene#12763]
### Description

The failure looks related to PR: https://github.com/apache/lucene/pull/12549
```
   >     java.lang.AssertionError
   >         at __randomizedtesting.SeedInfo.seed([35A934187ED84C8:25118E30AE9A3838]:0)
   >         at org.junit.Assert.fail(Assert.java:87)
   >         at org.junit.Assert.assertTrue(Assert.java:42)
   >         at org.junit.Assert.assertFalse(Assert.java:65)
   >         at org.junit.Assert.assertFalse(Assert.java:75)
   >         at org.apache.lucene.index.TestIndexWriter.testHasUncommittedChanges(TestIndexWriter.java:2404)
   >         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   >         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

### Gradle command to reproduce

gradlew :lucene:core:test --tests "org.apache.lucene.index.TestIndexWriter.testHasUncommittedChanges" -Ptests.jvms=1 -Ptests.jvmargs= -Ptests.seed=35A934187ED84C8 -Ptests.gui=true -Ptests.file.encoding=UTF-8 -Ptests.vectorsize=512

**Comment by dweiss** [comment]
Here's another seed where it's failing (from a PR):
```
gradlew :lucene:core:test --tests "org.apache.lucene.index.TestIndexWriter.testHasUncommittedChanges" -Ptests.jvms=2 -Ptests.jvmargs= -Ptests.seed=220BFF32E4498225 -Ptests.gui=true -Ptests.file.encoding=US-ASCII -Ptests.vectorsize=128
```

**Comment by jpountz** [comment]
I'm away from my main working computer this week, I suspect it's a similar issue that I saw elsewhere where merges cascade. I'll look into it on Monday if nobody beats me to me.
