### ISSUE TITLE
Reproducible error in TestLucene90HnswVectorsFormat.testIndexedValueNotAliased 

### ISSUE THREAD

**Issue by iverase** [apache/lucene#12840]
Command to reproduce:

```
./gradlew test --tests TestLucene90HnswVectorsFormat.testIndexedValueNotAliased -Dtests.seed=611EEBD0148F03C7
```

error:
```
org.apache.lucene.backward_codecs.lucene90.TestLucene90HnswVectorsFormat > testIndexedValueNotAliased FAILED
    java.lang.AssertionError: expected:<1.0> but was:<2.0>
        at __randomizedtesting.SeedInfo.seed([611EEBD0148F03C7:651A742B93C1394]:0)
        at junit@4.13.1/org.junit.Assert.fail(Assert.java:89)
        at junit@4.13.1/org.junit.Assert.failNotEquals(Assert.java:835)
        at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:577)
        at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:701)
```

**Comment by benwtrent** [comment]
fixed via: https://github.com/apache/lucene/pull/12848
