### ISSUE TITLE
org.apache.lucene.search.TestByteVectorSimilarityQuery.testApproximate failing intermittently

### ISSUE THREAD

**Issue by msfroh** [apache/lucene#13009]
### Description

Sorry -- I accidentally labeled it "type:task" and now I can't move it to "type:test". 

### Failure
```
org.apache.lucene.search.TestByteVectorSimilarityQuery > testApproximate FAILED
    java.lang.UnsupportedOperationException
        at __randomizedtesting.SeedInfo.seed([5D3CBCC19F394DBA:55EAB2739217D945]:0)
        at org.apache.lucene.search.TestByteVectorSimilarityQuery$1.createVectorScorer(TestByteVectorSimilarityQuery.java:81)
        at org.apache.lucene.search.AbstractVectorSimilarityQuery$1.scorer(AbstractVectorSimilarityQuery.java:148)
        at org.apache.lucene.search.Weight.scorerSupplier(Weight.java:135)
        at org.apache.lucene.search.Weight.bulkScorer(Weight.java:167)
        at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.bulkScorer(LRUQueryCache.java:930)
        at org.apache.lucene.tests.search.AssertingWeight.bulkScorer(AssertingWeight.java:122)
        at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.bulkScorer(LRUQueryCache.java:930)
        at org.apache.lucene.tests.search.AssertingWeight.bulkScorer(AssertingWeight.java:122)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:678)
        at org.apache.lucene.tests.search.AssertingIndexSearcher.search(AssertingIndexSearcher.java:79)
        at org.apache.lucene.search.IndexSearcher.lambda$search$2(IndexSearcher.java:636)
        at org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:117)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Reproduce with
```
gradlew :lucene:core:test --tests "org.apache.lucene.search.TestByteVectorSimilarityQuery.testApproximate" -Ptests.jvms=2 \
 -Ptests.jvmargs= -Ptests.seed=5D3CBCC19F394DBA -Ptests.gui=true -Ptests.file.encoding=UTF-8 -Ptests.vectorsize=512
```

**Comment by zhaih** [comment]
I think that test case doesn't work well with simple text codec as that codec will always visit documents upto limit (which is the cardinality of the acceptDoc), however the test will basically fail with the exception above after it visit to the limit. I'll open a PR to just not using the SimpleTextCodec if it is randomly chosen.
