### ISSUE TITLE
No static method version()  crash in android project

### ISSUE THREAD

**Issue by bjhexn** [apache/lucene#13078]
### Description

private fun createIndex(): IndexWriter {
        val path = Path(getDir("lunece", 0).path)
        val fsDirectory = FSDirectory.open(path) 
        val analyzer = StandardAnalyzer()
        val config = IndexWriterConfig(analyzer)
         return IndexWriter(fsDirectory, config)
    }

 java.lang.NoSuchMethodError: No static method version()Ljava/lang/Runtime$Version; in class Ljava/lang/Runtime; or its super classes (declaration of 'java.lang.Runtime' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at org.apache.lucene.util.Constants.<clinit>(Constants.java:40)
                                                                                                    	at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:161)
                                                                                                    	at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:156)
                                                                                                    	at com.myapp.newest.MainActivity.createIndex(MainActivity.kt:46)

### Version and environment details

version:
 implementation("org.apache.lucene:lucene-core:9.9.2")
 implementation("org.apache.lucene:lucene-queryparser:9.9.2")
 implementation("org.apache.lucene:lucene-analysis-common:9.9.2") 
environment:
 Android project

**Comment by uschindler** [comment]
Android is not a supported platform. The official `java.lang.Runtime` class has a static `version()` method. So your setup does not follow the Java specification and we won't change this.

Reference: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Runtime.html#version()

Please report this to the Dalvik runtime.
