### ISSUE TITLE
TestTopFieldCollector.testTotalHits test failure

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#13080]
### Description

TestTopFieldCollector.testTotalHits fails on branch_9x, git-bisect indicates https://github.com/apache/lucene/commit/0aa88910ca9a1032d288996d14203eac4953f2de

I tried reproducing on `main` but it didn't fail

```
org.apache.lucene.search.TestTopFieldCollector > testTotalHits FAILED
    java.lang.AssertionError: expected:<2> but was:<3>
        at __randomizedtesting.SeedInfo.seed([71EA3D3296E5473E:5B9A6F84977235B9]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.apache.lucene.search.TestTopFieldCollector.testTotalHits(TestTopFieldCollector.java:194)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

### Gradle command to reproduce

./gradlew test --tests TestTopFieldCollector.testTotalHits -Dtests.seed=71EA3D3296E5473E -Dtests.locale=en-HK -Dtests.timezone=Australia/West -Dtests.asserts=true -Dtests.file.encoding=UTF-8

**Comment by benwtrent** [comment]
Ah, I see the issue, will fix momentarily.
