### ISSUE TITLE
TestFSTs.testRandomWords reproducible NPE

### ISSUE THREAD

**Issue by stefanvodita** [apache/lucene#13174]
### Description

`./gradlew :lucene:core:test --tests "org.apache.lucene.util.fst.TestFSTs.testRandomWords" -Ptests.seed=5E5E16BC74CD0647`

```
org.apache.lucene.util.fst.TestFSTs > testRandomWords FAILED
    java.lang.NullPointerException: Cannot invoke "org.apache.lucene.util.fst.FST.getMetadata()" because "fst" is null
        at __randomizedtesting.SeedInfo.seed([5E5E16BC74CD0647:20CFAD83BDC2A982]:0)
        at org.apache.lucene.tests.util.fst.FSTTester.doTest(FSTTester.java:291)
        at org.apache.lucene.util.fst.TestFSTs.doTest(TestFSTs.java:217)
        at org.apache.lucene.util.fst.TestFSTs.testRandomWords(TestFSTs.java:306)
        at org.apache.lucene.util.fst.TestFSTs.testRandomWords(TestFSTs.java:281)
```

**Comment by tteofili** [comment]
I don't seem to be able to reproduce it at the moment, was this observed on `main` branch?

**Comment by stefanvodita** [comment]
I ran into this while working on an old branch. I can reproduce it on `main` at commit [ba81826951c1f628efb60c6165add27601173bd9](https://github.com/apache/lucene/commit/ba81826951c1f628efb60c6165add27601173bd9).

**Comment by slow-J** [comment]
Should we close this if this issue no longer manifests? I cannot repro on `main` at the newest commit https://github.com/apache/lucene/commit/30c965ea575a5e75c2bf724a340aa690d82f1ec5.

**Comment by stefanvodita** [comment]
It's likely that an issue might no longer be reproducible on a more recent commit because an unrelated change would have impacted the random numbers we generate. I wouldn't assume that this issue is fixed now.
