### ISSUE TITLE
TestPackedInts.testPackedLongValues failing

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#13249]
### Description

TestPackedInts.testPackedLongValues fails repeatably, example trace:

```
org.apache.lucene.util.packed.TestPackedInts > testPackedLongValues FAILED
    java.lang.AssertionError: expected:<2368> but was:<2384>
        at __randomizedtesting.SeedInfo.seed([E73C4D01E8CF65EC:E32957873BE4F660]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.apache.lucene.util.packed.TestPackedInts.testPackedLongValues(TestPackedInts.java:1022)
```

### Gradle command to reproduce

./gradlew :lucene:core:test --tests "org.apache.lucene.util.packed.TestPackedInts.testPackedLongValues" -Ptests.jvms=2 -Ptests.jvmargs= -Ptests.seed=E73C4D01E8CF65EC -Ptests.gui=true -Ptests.file.encoding=US-ASCII -Ptests.vectorsize=128

**Comment by benwtrent** [comment]
Git bisect shows: c41eb227ea7b569b2df112d0cfdd1f2cc3459f9d

https://github.com/apache/lucene/pull/13232

@original-brownbear mind taking a look?

**Comment by original-brownbear** [comment]
@benwtrent sure thing taking a look!

**Comment by original-brownbear** [comment]
Here we go: https://github.com/apache/lucene/pull/13250 turns out we need to be a little tricky here after all for singletons + ram estimation.
