### ISSUE TITLE
Reproducible failure TestIndexWriterExceptions2.testBasics

### ISSUE THREAD

**Issue by ChrisHegarty** [apache/lucene#13377]
```
gradlew test --tests TestIndexWriterExceptions2.testBasics -Dtests.seed=8D4903C430CE15F -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

```
org.apache.lucene.index.TestIndexWriterExceptions2 > testBasics FAILED
    java.lang.NegativeArraySizeException: -4
        at __randomizedtesting.SeedInfo.seed([8D4903C430CE15F:350C3E107BE2BF2F]:0)
        at org.apache.lucene.util.bkd.BKDWriter.writeFieldNDims(BKDWriter.java:522)
        at org.apache.lucene.util.bkd.BKDWriter.writeField(BKDWriter.java:436)
        at org.apache.lucene.codecs.lucene90.Lucene90PointsWriter.writeField(Lucene90PointsWriter.java:142)
        at org.apache.lucene.tests.codecs.asserting.AssertingPointsFormat$AssertingPointsWriter.writeField(AssertingPointsFormat.java:128)
        at org.apache.lucene.tests.codecs.cranky.CrankyPointsFormat$CrankyPointsWriter.writeField(CrankyPointsFormat.java:63)
        at org.apache.lucene.index.PointValuesWriter.flush(PointValuesWriter.java:227)
        at org.apache.lucene.index.IndexingChain.writePoints(IndexingChain.java:390)
        at org.apache.lucene.index.IndexingChain.flush(IndexingChain.java:298)
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:456)
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:496)
        at org.apache.lucene.index.DocumentsWriter.maybeFlush(DocumentsWriter.java:450)
        at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:643)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:575)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:112)
        at org.apache.lucene.index.TestIndexWriterExceptions2.testBasics(TestIndexWriterExceptions2.java:221)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1583)

org.apache.lucene.index.TestIndexWriterExceptions2 > test suite's output saved to /Users/chegar/git/lucene_msscorer/lucene/lucene/core/build/test-results/test/outputs/OUTPUT-org.apache.lucene.index.TestIndexWriterExceptions2.txt, copied below:
  1> Unexpected exception: dumping fake-exception-log:...
  1> 
  1> TEST: got expected fake exc:Fake IOException from DocValuesConsumer.addSortedNumericField()
  1> java.io.IOException: Fake IOException from DocValuesConsumer.addSortedNumericField()
  1>    at org.apache.lucene.tests.codecs.cranky.CrankyDocValuesFormat$CrankyDocValuesConsumer.addSortedNumericField(CrankyDocValuesFormat.java:101)
  1>    at org.apache.lucene.index.SortedNumericDocValuesWriter.flush(SortedNumericDocValuesWriter.java:205)
  1>    at org.apache.lucene.index.IndexingChain.writeDocValues(IndexingChain.java:433)
  1>    at org.apache.lucene.index.IndexingChain.flush(IndexingChain.java:291)
  1>    at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:456)
  1>    at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:496)
  1>    at org.apache.lucene.index.DocumentsWriter.maybeFlush(DocumentsWriter.java:450)
  1>    at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:643)
  1>    at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3672)
  1>    at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:4120)
  1>    at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:4082)
  1>    at org.apache.lucene.index.TestIndexWriterExceptions2.testBasics(TestIndexWriterExceptions2.java:227)
  1>    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  1>    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  1>    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  1>    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  1>    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  1>    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  1>    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  1>    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  1>    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  1>    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  1>    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  1>    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
...
```

**Comment by ChrisHegarty** [comment]
This test started failing as a result of #13369.
