### ISSUE TITLE
Reproducible test failure in TestTaxonomyFacetAssociations.testFloatSumAssociation -- ULP float issue?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#13720]
### Description

@uschindler's Windows CI build [caught this failing test+seed](https://jenkins.thetaphi.de/job/Lucene-MMAPv2-Windows/1517/), and it repros on my Linux dev box too:

```
org.apache.lucene.facet.taxonomy.TestTaxonomyFacetAssociations > test suite's output saved to /s1/l/trunk/lucene/facet/build/test-results/test/outputs/OUTPUT-org.apache.lucene.facet.taxonomy.TestTaxonomyFacetAssociations.txt, cop\
ied below:
  2> Sep 05, 2024 8:59:40 AM org.apache.lucene.internal.vectorization.VectorizationProvider lookup
  2> WARNING: Vector bitsize and/or integer vectors enforcement; using default vectorization provider outside of testMode
   >     java.lang.AssertionError: expected:<1832078.0> but was:<1832078.25>
   >         at __randomizedtesting.SeedInfo.seed([DCA9002AF6829540:B1E122AE39E2A1D]:0)
   >         at junit@4.13.1/org.junit.Assert.fail(Assert.java:89)
   >         at junit@4.13.1/org.junit.Assert.failNotEquals(Assert.java:835)
   >         at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:555)
   >         at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:685)
   >         at org.apache.lucene.facet.taxonomy.TestTaxonomyFacetAssociations.assertFloatFacetResultsEqual(TestTaxonomyFacetAssociations.java:657)
   >         at org.apache.lucene.facet.taxonomy.TestTaxonomyFacetAssociations.testFloatSumAssociation(TestTaxonomyFacetAssociations.java:330)
   >         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
   >         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
   >         at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
   >         at java.base/java.lang.Thread.run(Thread.java:1570)
  2> NOTE: reproduce with: gradlew test --tests TestTaxonomyFacetAssociations.testFloatSumAssociation -Dtests.seed=DCA9002AF6829540 -Dtests.directory=MMapDirectory -Dtests.locale=en-FI -Dtests.timezone=Hongkong -Dtests.asserts=tr\
ue -Dtests.file.encoding=UTF-8
  2> NOTE: leaving temporary files on disk at: /s1/l/trunk/lucene/facet/build/tmp/tests-tmp/lucene.facet.taxonomy.TestTaxonomyFacetAssociations_DCA9002AF6829540-001
  2> NOTE: test params are: codec=Lucene912, sim=Asserting(RandomSimilarity(queryNorm=true): {match=IB LL-L2}), locale=en-FI, timezone=Hongkong
  2> NOTE: Linux 6.9.7-arch1-1 amd64/Arch Linux 22.0.2 (64-bit)/cpus=1,threads=1,free=302182328,total=348127232
  2> NOTE: All tests run in this JVM: [TestTaxonomyFacetAssociations]
```

It looks likely this is an OB1 float ULP issue, maybe wrong/different order of float operations between the test and the facet association code?

**Comment by uschindler** [comment]
I marked this failing build as persistent until this is fixed.

**Comment by stefanvodita** [comment]
It's one of those float-summation-is-not-commutative errors.
First ordering:
```
  1> 0.0 + 575310.1 = 575310.1
  1> 575310.1 + 701147.2 = 1276457.2
  1> 1276457.2 + 555620.8 = 1832078.0
```
Second ordering:
```
  1> 0.0 + 575310.1 = 575310.1
  1> 575310.1 + 555620.8 = 1130931.0
  1> 1130931.0 + 701147.2 = 1832078.2
```
The results are compared with an epsilon of 0.2. The short-term solution can be to increase that even more. The long-term solution can be #13011.

**Comment by mikemccand** [comment]
I wish the test assert APIs allowed us to express the allowed epsilon in ULPs (1 or 2 or so), not a fixed float.

The expected/allowed absolute error varies with how large the float is.  In this case 0.25 is 2 ULPs at 1832078.25 for `float32` I think.

**Comment by stefanvodita** [comment]
I like the idea of comparing based on ULP! I'll poach some code for [float comparison](https://github.com/apache/commons-numbers/blob/master/commons-numbers-core/src/main/java/org/apache/commons/numbers/core/Precision.java#L224) from Apache Commons Numbers.

**Comment by mikemccand** [comment]
> I like the idea of comparing based on ULP! I'll poach some code for [float comparison](https://github.com/apache/commons-numbers/blob/master/commons-numbers-core/src/main/java/org/apache/commons/numbers/core/Precision.java#L224) from Apache Commons Numbers.

Whoa, very cool, the impl already exists!  Thank you Apache Commons, and @stefanvodita for finding this.
