### ISSUE TITLE
TestPerFieldDocValuesFormat.testThreads2 fails with  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ChrisHegarty** [apache/lucene#13798]
Fails on main and 9.x

```
gradlew test --tests TestPerFieldDocValuesFormat -Dtests.seed=9BD00EA6CD907A21 -Dtests.nightly=true -Dtests.locale=gv -Dtests.timezone=America/Juneau -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

```
TestPerFieldDocValuesFormat > testThreads2 FAILED
    java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot commit
        at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:5582)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3784)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:4125)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:4087)
        at org.apache.lucene.tests.index.RandomIndexWriter.commit(RandomIndexWriter.java:414)
        at org.apache.lucene.tests.index.RandomIndexWriter.commit(RandomIndexWriter.java:370)
        at org.apache.lucene.tests.index.LegacyBaseDocValuesFormatTestCase.testThreads2(LegacyBaseDocValuesFormatTestCase.java:2952)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1575)

        Caused by:
        java.lang.ArrayIndexOutOfBoundsException: Index 62 out of bounds for length 56
            at org.apache.lucene.util.packed.Packed64.get(Packed64.java:80)
            at org.apache.lucene.index.OrdinalMap$1.get(OrdinalMap.java:379)
            at org.apache.lucene.index.MultiDocValues$MultiSortedSetDocValues.nextOrd(MultiDocValues.java:937)
            at org.apache.lucene.index.SortedSetDocValuesWriter$DocOrds.<init>(SortedSetDocValuesWriter.java:450)
            at org.apache.lucene.index.SortingCodecReader$7.lambda$getSortedSet$4(SortingCodecReader.java:613)
            at org.apache.lucene.index.SortingCodecReader.getOrCreate(SortingCodecReader.java:722)
            at org.apache.lucene.index.SortingCodecReader.getOrCreateDV(SortingCodecReader.java:763)
            at org.apache.lucene.index.SortingCodecReader$7.getSortedSet(SortingCodecReader.java:609)
            at org.apache.lucene.codecs.DocValuesConsumer.mergeSortedSetField(DocValuesConsumer.java:807)
            at org.apache.lucene.codecs.DocValuesConsumer.merge(DocValuesConsumer.java:149)
            at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.merge(PerFieldDocValuesFormat.java:150)
            at org.apache.lucene.index.SegmentMerger.mergeDocValues(SegmentMerger.java:208)
            at org.apache.lucene.index.SegmentMerger.mergeWithLogging(SegmentMerger.java:334)
            at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:159)
            at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5283)
            at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4749)
            at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6567)
            at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:668)
            at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729)

```

**Comment by benwtrent** [comment]
Intra merge concurrency is causing a race condition here it seems? I can debug where.

**Comment by benwtrent** [comment]
Reverting point value parallelism fixes this bug. This tells me that with how merging point values from multiple threads is busted. I will see if there is a quick fix. If there isn't I vote we do not merge points in parallel.

**Comment by benwtrent** [comment]
Ah, looking at the `clone` code for merge state @jpountz

```
    for (int i = 0; i < storedFieldsReaders.length; ++i) {
      if (storedFieldsReaders[i] != null) {
        storedFieldsReaders[i] = storedFieldsReaders[i].getMergeInstance();
      }
      if (termVectorsReaders[i] != null) {
        termVectorsReaders[i] = termVectorsReaders[i].getMergeInstance();
      }
      if (normsProducers[i] != null) {
        normsProducers[i] = normsProducers[i].getMergeInstance();
      }
      if (docValuesProducers[i] != null) {
        docValuesProducers[i] = docValuesProducers[i].getMergeInstance();
      }
      if (fieldsProducers[i] != null) {
        fieldsProducers[i] = fieldsProducers[i].getMergeInstance();
      }
      if (pointsReaders[i] != null) {
        pointsReaders[i] = pointsReaders[i].getMergeInstance();
      }
      if (knnVectorsReaders[i] != null) {
        knnVectorsReaders[i] = knnVectorsReaders[i].getMergeInstance();
      }
    }
```
This assumes `getMergeInstance()` does something. But points simply returns `this`. 

I am thinking that sharing a `reader` between threads is always a bad idea.

**Comment by jpountz** [comment]
Wow, thanks for finding this, it's indeed broken. I'll look into it.

**Comment by benwtrent** [comment]
@jpountz given the feature freeze of 9.12, what do you think of disabling intra-merge parallelism for everything :/ and we enable it one at a time for things in the future as wrinkles are worked out?

**Comment by jpountz** [comment]
Agreed, this sounds safer with 9.12 around the corner.

**Comment by benwtrent** [comment]
@jpountz I will do that. But, keep the testing that provides the parallelism to ensure we are covered when things are enabled in the future

**Comment by luyuncheng** [comment]
hi, @benwtrent @jpountz 
we try to use [#13190](https://github.com/apache/lucene/pull/13190)  parallel forcemerge segments. and we found this issue comes from [#13475](https://github.com/apache/lucene/pull/13475) it occurs as followings stack:

when parallel merge in docvalues:

1. clone merge state:
https://github.com/benwtrent/lucene/blob/92eb78d6a23e01a0a00bb065a1b9933d167291fe/lucene/core/src/java/org/apache/lucene/index/SegmentMerger.java#L204-L210

```
  private void mergeDocValues(
      SegmentWriteState segmentWriteState, SegmentReadState segmentReadState) throws IOException {
    MergeState mergeState = mergeState();
    try (DocValuesConsumer consumer = codec.docValuesFormat().fieldsConsumer(segmentWriteState)) {
      consumer.merge(mergeState);
    }
  }
```

2. new instance

`MergeState mergeState = mergeState();` would clone readers 
```
      if (docValuesProducers[i] != null) {
        docValuesProducers[i] = docValuesProducers[i].getMergeInstance();
      }
```

getMergeInstance return new `Lucene90DocValuesProducer`
https://github.com/benwtrent/lucene/blob/cd88a97a63a97dc857d692ec3eb73b229bb5f372/lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java#L168-L181

3. buffer reset

new `Lucene90DocValuesProducer` it would do IndexInput data clone: `this.data = data.clone();`  when IndexInput is `NIOFSIndexInput` it would do `BufferedIndexInput#clone()` 

when parallel get `MergeState mergeState = mergeState();` and buffer reset to `EMPTY_BYTEBUFFER` 

===
so we think parallel error comes from mergeState() clone
