### ISSUE TITLE
TestBestSpeedLucene80DocValuesFormat fails dv for field: sorted_set has ords out of order

### ISSUE THREAD

**Issue by ChrisHegarty** [apache/lucene#13808]
Fails on the 9x branch, but not reproducible on _main_. 

```
ERROR: The following test(s) have failed:
  - org.apache.lucene.backward_codecs.lucene80.TestBestSpeedLucene80DocValuesFormat.testSparseDocValuesVsStoredFields (:lucene:backward-codecs)
    Test output: /Users/chegar/git/lucene_msscorer/lucene/lucene/backward-codecs/build/test-results/test/outputs/OUTPUT-org.apache.lucene.backward_codecs.lucene80.TestBestSpeedLucene80DocValuesFormat.txt
    Reproduce with: gradlew :lucene:backward-codecs:test --tests "org.apache.lucene.backward_codecs.lucene80.TestBestSpeedLucene80DocValuesFormat.testSparseDocValuesVsStoredFields" -Ptests.jvms=6 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1" -Ptests.seed=FF36FB24D11EF90B -Ptests.iters=1 -Ptests.multiplier=3 -Ptests.locale=wo-Latn-SN -Ptests.timezone=Australia/Canberra -Ptests.gui=false -Ptests.file.encoding=UTF-8 -Ptests.vectorsize=512 -Ptests.forceintegervectors=true
```

```
TestBestSpeedLucene80DocValuesFormat > testSparseDocValuesVsStoredFields FAILED
    org.apache.lucene.index.CheckIndex$CheckIndexException: dv for field: sorted_set has ords out of order: [2d 35 35 39 32 35 39 35 33 39 38 33 30 33 34 30 37 39 35 31] >=[2d 32 33 32 38 34 39 36 30 36 32 39 35 36 32 38 39 33 32 31]
        at __randomizedtesting.SeedInfo.seed([FF36FB24D11EF90B:ABED27372B92DF44]:0)
        at app/org.apache.lucene.core@9.12.0-SNAPSHOT/org.apache.lucene.index.CheckIndex.checkSortedSetDocValues(CheckIndex.java:3586)
        at app/org.apache.lucene.core@9.12.0-SNAPSHOT/org.apache.lucene.index.CheckIndex.checkDocValues(CheckIndex.java:3680)
        at app/org.apache.lucene.core@9.12.0-SNAPSHOT/org.apache.lucene.index.CheckIndex.testDocValues(CheckIndex.java:3258)
        at app/org.apache.lucene.core@9.12.0-SNAPSHOT/org.apache.lucene.index.CheckIndex.testSegment(CheckIndex.java:1096)
        at app/org.apache.lucene.core@9.12.0-SNAPSHOT/org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:800)
        at app/org.apache.lucene.core@9.12.0-SNAPSHOT/org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:567)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestUtil.checkIndex(TestUtil.java:345)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.store.MockDirectoryWrapper.close(MockDirectoryWrapper.java:918)
        at app//org.apache.lucene.backward_codecs.lucene80.BaseLucene80DocValuesFormatTestCase.doTestSparseDocValuesVsStoredFields(BaseLucene80DocValuesFormatTestCase.java:273)
        at app//org.apache.lucene.backward_codecs.lucene80.BaseLucene80DocValuesFormatTestCase.testSparseDocValuesVsStoredFields(BaseLucene80DocValuesFormatTestCase.java:159)
        at java.base@22.0.2/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base@22.0.2/java.lang.reflect.Method.invoke(Method.java:580)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app/junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app/org.apache.lucene.test_framework@9.12.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at app/junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at app/randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base@22.0.2/java.lang.Thread.run(Thread.java:1570)
...
```

**Comment by ChrisHegarty** [comment]
git bisect shows this:

```
ad09777867d10cbaa2a9582bb49a2de5ad7748ba is the first bad commit
commit ad09777867d10cbaa2a9582bb49a2de5ad7748ba
Author: Benjamin Trent <ben.w.trent@gmail.com>
Date:   Wed Sep 11 09:14:50 2024 -0400

    This commit adds a new test CMS that always provides intra-merge parallelism (#13475)
    
    @iverase has uncovered a potential issue with intra-merge CMS parallelism.
    
    This commit helps expose this problem by forcing tests to use intra-merge parallelism instead of always (well, usually) delegating to a SameThreadExecutorService.
    
    When intra-merge parallelism is used, norms, doc_values, stored_values, etc. are all merged in a separate thread than the thread that was used to construct their merge optimized instances.
    
    This trips assertions numerous assertions in AssertingCodec.assertThread where we assume that the thread that called getMergeInstance() is also the thread getting the values to merge.
    
    In addition to the better testing, this corrects poor merge state handling in the event of parallelism.

 lucene/CHANGES.txt                                 |  2 +
 .../java/org/apache/lucene/index/MergeState.java   | 53 +++++++++++++++++++++-
 .../org/apache/lucene/index/SegmentMerger.java     | 41 ++++++++++-------
 .../lucene/index/TestIndexWriterForceMerge.java    |  1 +
 .../apache/lucene/tests/util/LuceneTestCase.java   | 21 +++++++--
 5 files changed, 98 insertions(+), 20 deletions(-)
bisect found first bad commit
```

**Comment by ChrisHegarty** [comment]
Hmm.. that commit was reverted. Maybe that's confusing git bisect! ?

**Comment by benwtrent** [comment]
Since this has to do with merging sorted things, the field number change is a likely cause here as well.
