### ISSUE TITLE
TestTieredMergePolicy.testSimulateAppendOnly fails with AssertionError

### ISSUE THREAD

**Issue by ChrisHegarty** [apache/lucene#13818]
This failure has been reproduced on both the `main` and `branch_9_12` branches. Does not fail on `branch_9_11`.

```
ERROR: The following test(s) have failed:
  - org.apache.lucene.index.TestTieredMergePolicy.testSimulateAppendOnly (:lucene:core)
    Test output: /Users/chegar/git/lucene_msscorer/lucene/lucene/core/build/test-results/test/outputs/OUTPUT-org.apache.lucene.index.TestTieredMergePolicy.txt
    Reproduce with: gradlew :lucene:core:test --tests "org.apache.lucene.index.TestTieredMergePolicy.testSimulateAppendOnly" -Ptests.jvms=6 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1" -Ptests.seed=B90724898E61B17C -Ptests.multiplier=1 -Ptests.locale=bm -Ptests.timezone=America/Metlakatla -Ptests.nightly=true -Ptests.gui=false -Ptests.file.encoding=UTF-8 -Ptests.vectorsize=default -Ptests.forceintegervectors=false
```

```
TestTieredMergePolicy > testSimulateAppendOnly FAILED
    java.lang.AssertionError: mergeFactor=4 minSegmentBytes=38,046,720 maxMergedSegmentBytes=5,213,519,872 segmentsPerTier=4.00000 maxMergeAtOnce=24 numSegments=43 allowed=41.0000 totalBytes=8,132,505,600 delPercentage=0.00000 deletesPctAllowed=39.9912 targetNumSegments=32
        at __randomizedtesting.SeedInfo.seed([B90724898E61B17C:A00E580F25EF5FBA]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.apache.lucene.index.TestTieredMergePolicy.assertSegmentInfos(TestTieredMergePolicy.java:143)
        at org.apache.lucene.tests.index.BaseMergePolicyTestCase.doTestSimulateAppendOnly(BaseMergePolicyTestCase.java:446)
        at org.apache.lucene.index.TestTieredMergePolicy.testSimulateAppendOnly(TestTieredMergePolicy.java:931)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ChrisHegarty** [comment]
```
3ee37695af18246a4e05f8a6c7ee1ab7a2f8118f is the first bad commit
commit 3ee37695af18246a4e05f8a6c7ee1ab7a2f8118f
Author: Carlos Delgado <6339205+carlosdelest@users.noreply.github.com>
Date:   Wed Jul 17 13:54:19 2024 +0200

    Add target search concurrency to TieredMergePolicy (#13430)

 lucene/CHANGES.txt                                 |  6 +-
 .../org/apache/lucene/index/TieredMergePolicy.java | 80 ++++++++++++++++++----
 .../apache/lucene/index/TestTieredMergePolicy.java | 40 +++++++++--
 .../apache/lucene/tests/util/LuceneTestCase.java   |  6 ++
 4 files changed, 111 insertions(+), 21 deletions(-)
bisect found first bad commit
```

**Comment by ChrisHegarty** [comment]
`numSegments=43 allowed=41.0000`

**Comment by ChrisHegarty** [comment]
Specific failure details:

```
1> hasBalancedMerges=true because (maxMergedSegmentBytes * 1.5 <= totalMergeSize): 7.820279808E9 <=7880253440
  1> maxDocsPerSegment=49637, infos.totalMaxDoc()=1588380, totalDelCount=0
  1>  0 info:27871, info.getDelCount()=0
  1>  1 info:41428, info.getDelCount()=0
  1>  2 info:37588, info.getDelCount()=0
  1>  3 info:27811, info.getDelCount()=0
  1>  4 info:41742, info.getDelCount()=0
  1>  5 info:36493, info.getDelCount()=0
  1>  6 info:43727, info.getDelCount()=0
  1>  7 info:39064, info.getDelCount()=0
  1>  8 info:45585, info.getDelCount()=0
  1>  9 info:29545, info.getDelCount()=0
  1> 10 info:38498, info.getDelCount()=0
  1> 11 info:28778, info.getDelCount()=0
  1> 12 info:35942, info.getDelCount()=0
  1> 13 info:42968, info.getDelCount()=0
  1> 14 info:35234, info.getDelCount()=0
  1> 15 info:36601, info.getDelCount()=0
  1> 16 info:38059, info.getDelCount()=0
  1> 17 info:39679, info.getDelCount()=0
  1> 18 info:44779, info.getDelCount()=0
  1> 19 info:36235, info.getDelCount()=0
  1> 20 info:37079, info.getDelCount()=0
  1> 21 info:27881, info.getDelCount()=0
  1> 22 info:45866, info.getDelCount()=0
  1> 23 info:49268, info.getDelCount()=0
  1> 24 info:48118, info.getDelCount()=0
  1> 25 info:32317, info.getDelCount()=0
  1> 26 info:39347, info.getDelCount()=0
  1> 27 info:39240, info.getDelCount()=0
  1> 28 info:29737, info.getDelCount()=0
  1> 29 info:35858, info.getDelCount()=0
  1> 30 info:36470, info.getDelCount()=0
  1> 31 info:46808, info.getDelCount()=0
  1> 32 info:33012, info.getDelCount()=0
  1> 33 info:36416, info.getDelCount()=0
  1> 34 info:32081, info.getDelCount()=0
  1> 35 info:47434, info.getDelCount()=0
  1> 36 info:42246, info.getDelCount()=0
  1> 37 info:28896, info.getDelCount()=0
  1> 38 info:37594, info.getDelCount()=0
  1> 39 info:41601, info.getDelCount()=0
  1> 40 info:29874, info.getDelCount()=0
  1> 41 info:36179, info.getDelCount()=0
  1> 42 info:7431, info.getDelCount()=0
  1> (numSegments <= allowedSegCount)=false, hasBalancedMerges=true, eligibleDocsMerge=true
   >     java.lang.AssertionError: mergeFactor=4 minSegmentBytes=38,046,720 maxMergedSegmentBytes=5,213,519,872 segmentsPerTier=4.00000 maxMergeAtOnce=24 numSegments=43 allowed=41.0000 totalBytes=8,132,505,600 delPercentage=0.00000 deletesPctAllowed=39.9912 targetNumSegments=32

```

**Comment by ChrisHegarty** [comment]
It looks like the smallest two segment could have been merged - this is what the assertion complains about. 

```
  1> 0 info.maxDoc()=7431, info.getDelCount()=0
  1> 1 info.maxDoc()=27811, info.getDelCount()=0
```

Merging these will be much smaller than `maxDocsPerSegment=49637`.

**Comment by ChrisHegarty** [comment]
> It looks like the smallest two segment could have been merged - this is what the assertion complains about.
> 
> ```
>   1> 0 info.maxDoc()=7431, info.getDelCount()=0
>   1> 1 info.maxDoc()=27811, info.getDelCount()=0
> ```
> 
> Merging these will be much smaller than `maxDocsPerSegment=49637`, so they are certainly a candidate for merging. But doesn't look like too much of a problem - a little less aggressive than it possibly could be.

Ok, so these segments won't be merged because the size of the resulting segment would not be at least 50% larger than the biggest input segment.

After looking, I don't see a product bug here. But rather a test issue that does not account for a corner case.  @mikemccand @jpountz  ??

**Comment by mikemccand** [comment]
Whether it's test only issue or bug in TMP, this is quite minor corner case -- it should not be a blocker for 9.12.0.

**Comment by benwtrent** [comment]
In case its helpful, here is another failing seed for this: 
```
./gradlew test --tests TestTieredMergePolicy.testSimulateAppendOnly -Dtests.seed=12272834EAE8034A -Dtests.locale=bm-ML -Dtests.timezone=America/Bahia_Banderas -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

This really seems like a weird rounding error edge case or something. Its an off-by-one error for sure.
