### ISSUE TITLE
TestCommonTermsQuery.testMinShouldMatch test failure

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#13946]
### Description

git bisect indicated: b940511b07b

```
TestCommonTermsQuery > testMinShouldMatch FAILED
--
  | org.junit.ComparisonFailure: expected:<[2]> but was:<[3]>
  | at __randomizedtesting.SeedInfo.seed([574020B578DE2DA7:734828501FDB6F89]:0)
  | at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:117)
  | at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:146)
  | at org.apache.lucene.queries.TestCommonTermsQuery.testMinShouldMatch(TestCommonTermsQuery.java:256)
  | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  | at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  | at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  | at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  | at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  | at org.apache.lucene.test_framework@11.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  | at org.apache.lucene.test_framework@11.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at org.apache.lucene.test_framework@11.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  | at org.apache.lucene.test_framework@11.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  | at org.apache.lucene.test_framework@11.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  | at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

### Gradle command to reproduce

```
./gradlew :lucene:queries:test --tests "org.apache.lucene.queries.TestCommonTermsQuery.testMinShouldMatch" -Ptests.jvms=12 -Ptests.jvmargs= -Ptests.seed=574020B578DE2DA7 -Ptests.gui=true -Ptests.file.encoding=US-ASCII -Ptests.vectorsize=512 -Ptests.forceintegervectors=true
```

**Comment by benwtrent** [comment]
```  
1> 0 doc: 3 id: 0 score: 2.8378134
1> 1 doc: 0 id: 3 score: 0.16505925
1> 2 doc: 1 id: 2 score: 0.16505925
```

I think gitbisect might be a red herring?

It seems like its a typical failure where we tie break on the doc-id and but the docs have been merged and thus order has shifted.
