### ISSUE TITLE
TestPostingsUtil > testIntegerOverflow

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#13978]
### Description

Fails repeatably on current main. Didn't try other branches yet.
```
TestPostingsUtil > testIntegerOverflow FAILED
    java.lang.ArithmeticException: integer overflow
        at __randomizedtesting.SeedInfo.seed([118DF1D667E0B3C7:A472B2AD9A93BFD6]:0)
        at org.apache.lucene.util.GroupVIntUtil.toInt(GroupVIntUtil.java:224)
        at org.apache.lucene.util.GroupVIntUtil.writeGroupVInts(GroupVIntUtil.java:295)
        at org.apache.lucene.store.DataOutput.writeGroupVInts(DataOutput.java:356)
        at org.apache.lucene.codecs.lucene101.PostingsUtil.writeVIntBlock(PostingsUtil.java:64)
        at org.apache.lucene.codecs.lucene101.TestPostingsUtil.testIntegerOverflow(TestPostingsUtil.java:39)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(Ran
```

### Gradle command to reproduce

```
./gradlew test --tests TestPostingsUtil.testIntegerOverflow -Dtests.seed=118DF1D667E0B3C7 -Dtests.locale=khq-ML -Dtests.timezone=Etc/GMT+2 -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

**Comment by benwtrent** [comment]
OK, git bisect says: cfdd20f5bc8387ba24653ca2ba15aa5be10d0ae0

That bisect seems correct.

//CC @jpountz

**Comment by jpountz** [comment]
Woops, I'll look, thanks for bisecting!
