### ISSUE TITLE
mockfilesystem tests fail with IBM jdk [LUCENE-6517]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#7575]
Test failures look like this:
```
   [junit4] Suite: org.apache.lucene.mockfile.TestVerboseFS
   [junit4]   2> NOTE: reproduce with: ant test  -Dtestcase=TestVerboseFS -Dtests.method=testURI -Dtests.seed=A5E55A5C894B6526 -Dtests.locale=lt_LT -Dtests.timezone=America/Marigot -Dtests.asserts=true -Dtests.file.encoding=UTF-8
   [junit4] FAILURE 0.32s J1 | TestVerboseFS.testURI <<<
   [junit4]    > Throwable #1: java.lang.AssertionError: expected:</home/rmuir/workspace/trunk-ibm/lucene/build/test-framework/test/J1/temp/lucene.mockfile.TestVerboseFS A5E55A5C894B6526-001/tempDir-010/中国> but was:</home/rmuir/workspace/trunk-ibm/lucene/build/test-framework/test/J1/temp/lucene.mockfile.TestVerboseFS A5E55A5C894B6526-001/tempDir-010/-ý>
   [junit4]    > 	at __randomizedtesting.SeedInfo.seed([A5E55A5C894B6526:2C5721F741543F17]:0)
   [junit4]    > 	at org.apache.lucene.mockfile.MockFileSystemTestCase.testURI(MockFileSystemTestCase.java:72)
   [junit4]    > 	at java.lang.Thread.run(Thread.java:785)
   [junit4]   2> NOTE: leaving temporary files on disk at: /home/rmuir/workspace/trunk-ibm/lucene/build/test-framework/test/J1/temp/lucene.mockfile.TestVerboseFS A5E55A5C894B6526-001
   [junit4]   2> NOTE: test params are: codec=Asserting(Lucene50): {}, docValues:{}, sim=RandomSimilarityProvider(queryNorm=true,coord=no): {}, locale=lt_LT, timezone=America/Marigot
   [junit4]   2> NOTE: Linux 3.13.0-49-generic amd64/IBM Corporation 1.8.0 (64-bit)/cpus=8,threads=1,free=1578528,total=13041664
   [junit4]   2> NOTE: All tests run in this JVM: [TestVerboseFS]
   [junit4] Completed [4/36] on J1 in 0.97s, 14 tests, 1 failure <<< FAILURES!
```

I think its a JDK bug. I've posted a small testcase here:

https://developer.ibm.com/answers/questions/194536/bug-in-pathtouri-with-the-default-filesystem-provi.html

---
Migrated from [LUCENE-6517](https://issues.apache.org/jira/browse/LUCENE-6517) by Robert Muir (@rmuir), updated Aug 10 2015

**Comment by uschindler** [comment]
This should no longer be an issue, as OpenJ9 uses the OpenJDK class library now.
