### ISSUE TITLE
org.apache.xerces.util is a protected pkg on IBM J9 [LUCENE-6521]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#7579]
Benchmarks tests fail like this currently, due to cyberneko evilness:
```
   [junit4] ERROR   0.01s J2 | TestHtmlParser.testTitle <<<
   [junit4]    > Throwable #1: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.org.apache.xerces.util")
   [junit4]    > 	at __randomizedtesting.SeedInfo.seed([7BEED366A25D3140:3F8A9D3571212953]:0)
   [junit4]    > 	at java.security.AccessController.throwACE(AccessController.java:157)
   [junit4]    > 	at java.security.AccessController.checkPermissionHelper(AccessController.java:216)
   [junit4]    > 	at java.security.AccessController.checkPermission(AccessController.java:263)
   [junit4]    > 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:562)
   [junit4]    > 	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1655)
   [junit4]    > 	at java.lang.J9VMInternals$2.run(J9VMInternals.java:255)
   [junit4]    > 	at java.security.AccessController.doPrivileged(AccessController.java:529)
   [junit4]    > 	at java.lang.J9VMInternals.checkPackageAccess(J9VMInternals.java:253)
   [junit4]    > 	at java.lang.ClassLoader.defineClassImpl(Native Method)
   [junit4]    > 	at java.lang.ClassLoader.defineClass(ClassLoader.java:345)
   [junit4]    > 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
   [junit4]    > 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:727)
   [junit4]    > 	at java.net.URLClassLoader.access$400(URLClassLoader.java:95)
   [junit4]    > 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1178)
   [junit4]    > 	at java.security.AccessController.doPrivileged(AccessController.java:595)
   [junit4]    > 	at java.net.URLClassLoader.findClass(URLClassLoader.java:602)
   [junit4]    > 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:797)
   [junit4]    > 	at java.lang.ClassLoader.loadClass(ClassLoader.java:771)
   [junit4]    > 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
   [junit4]    > 	at java.lang.ClassLoader.loadClass(ClassLoader.java:752)
   [junit4]    > 	at org.cyberneko.html.parsers.SAXParser.<init>(SAXParser.java:38)
   [junit4]    > 	at org.apache.lucene.benchmark.byTask.feeds.DemoHTMLParser$Parser.<init>(DemoHTMLParser.java:55)
   [junit4]    > 	at org.apache.lucene.benchmark.byTask.feeds.DemoHTMLParser$Parser.<init>(DemoHTMLParser.java:51)
   [junit4]    > 	at org.apache.lucene.benchmark.byTask.feeds.TestHtmlParser.testTitle(TestHtmlParser.java:89)
   [junit4]    > 	at java.lang.Thread.run(Thread.java:785)
```

Root cause: https://github.com/ecologylab/cyberneko/blob/master/src/org/cyberneko/html/HTMLConfiguration.java#L200-L206

---
Migrated from [LUCENE-6521](https://issues.apache.org/jira/browse/LUCENE-6521) by Robert Muir (@rmuir), updated Jun 22 2015

**Comment by uschindler** [comment]
This is fixed in J9, as it now uses OpenJDK class library.
