### ISSUE TITLE
Reproducible fieldcache AIOOBE only on J9 [LUCENE-6522]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#7580]
Haven't dug in yet, just:
- reproduces easily on J9
- does not happen on Oracle JVM

```
   [junit4] Suite: org.apache.lucene.uninverting.TestFieldCacheVsDocValues
   [junit4] IGNOR/A 0.51s J2 | TestFieldCacheVsDocValues.testHugeBinaryValueLimit
   [junit4]    > Assumption #1: test requires codec with limits on max binary field length
   [junit4]   2> NOTE: reproduce with: ant test  -Dtestcase=TestFieldCacheVsDocValues -Dtests.method=testSortedSetFixedLengthVsUninvertedField -Dtests.seed=831619B333C362E6 -Dtests.locale=es_UY -Dtests.timezone=Atlantic/Bermuda -Dtests.asserts=true -Dtests.file.encoding=US-ASCII
   [junit4] ERROR   0.54s J2 | TestFieldCacheVsDocValues.testSortedSetFixedLengthVsUninvertedField <<<
   [junit4]    > Throwable #1: java.lang.ArrayIndexOutOfBoundsException
   [junit4]    > 	at __randomizedtesting.SeedInfo.seed([831619B333C362E6:B6EC641493EA4AD3]:0)
   [junit4]    > 	at org.apache.lucene.uninverting.DocTermOrds$OrdWrappedTermsEnum.seekCeil(DocTermOrds.java:692)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.assertEquals(TestFieldCacheVsDocValues.java:570)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.assertEquals(TestFieldCacheVsDocValues.java:511)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.doTestSortedSetVsUninvertedField(TestFieldCacheVsDocValues.java:385)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.testSortedSetFixedLengthVsUninvertedField(TestFieldCacheVsDocValues.java:105)
   [junit4]    > 	at java.lang.Thread.run(Thread.java:785)
   [junit4]   2> NOTE: reproduce with: ant test  -Dtestcase=TestFieldCacheVsDocValues -Dtests.method=testSortedSetVariableLengthVsUninvertedField -Dtests.seed=831619B333C362E6 -Dtests.locale=es_UY -Dtests.timezone=Atlantic/Bermuda -Dtests.asserts=true -Dtests.file.encoding=US-ASCII
   [junit4] ERROR   0.42s J2 | TestFieldCacheVsDocValues.testSortedSetVariableLengthVsUninvertedField <<<
   [junit4]    > Throwable #1: java.lang.ArrayIndexOutOfBoundsException
   [junit4]    > 	at __randomizedtesting.SeedInfo.seed([831619B333C362E6:2AB51ED6D324E426]:0)
   [junit4]    > 	at org.apache.lucene.uninverting.DocTermOrds$OrdWrappedTermsEnum.seekCeil(DocTermOrds.java:692)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.assertEquals(TestFieldCacheVsDocValues.java:570)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.assertEquals(TestFieldCacheVsDocValues.java:511)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.doTestSortedSetVsUninvertedField(TestFieldCacheVsDocValues.java:385)
   [junit4]    > 	at org.apache.lucene.uninverting.TestFieldCacheVsDocValues.testSortedSetVariableLengthVsUninvertedField(TestFieldCacheVsDocValues.java:112)
   [junit4]    > 	at java.lang.Thread.run(Thread.java:785)
   [junit4]   2> NOTE: leaving temporary files on disk at: /home/rmuir/workspace/trunk-ibm/lucene/build/misc/test/J2/temp/lucene.uninverting.TestFieldCacheVsDocValues 831619B333C362E6-001
   [junit4]   2> NOTE: test params are: codec=Asserting(Lucene50): {indexed=FSTOrd50, id=Lucene50(blocksize=128)}, docValues:{dv=DocValuesFormat(name=Asserting), field=DocValuesFormat(name=Asserting)}, sim=DefaultSimilarity, locale=es_UY, timezone=Atlantic/Bermuda
   [junit4]   2> NOTE: Linux 3.13.0-49-generic amd64/IBM Corporation 1.8.0 (64-bit)/cpus=8,threads=1,free=10179616,total=32243712
   [junit4]   2> NOTE: All tests run in this JVM: [TestDocTermOrds, TestNumericTerms32, TestFieldCacheVsDocValues]
   [junit4] Completed [21/25] on J2 in 4.50s, 10 tests, 2 errors, 1 skipped <<< FAILURES!
```

---
Migrated from [LUCENE-6522](https://issues.apache.org/jira/browse/LUCENE-6522) by Robert Muir (@rmuir), 1 vote, updated May 08 2018

**Comment by uschindler** [comment]
This seems fixed now, tets no longer fails.

**Comment by uschindler** [comment]
In addition, Lucene has no fieldcache anymore.
